### ISSUE TITLE
Loss of nanosecond resolution when constructing Timestamps from str

### ISSUE THREAD

**Issue by hcontrast** [pydata/pandas#10041]
Looks like a bug: When passing a YYYYMMDDTHHMMSS.f string to `pd.Timestamp`, the resolution seems limited to micro- rather than nano-seconds:

```python
>>> pd.Timestamp('20130101T000000.000001+0000')
Timestamp('2013-01-01 00:00:00.000001+0000', tz='UTC')

>>> pd.Timestamp('20130101T000000.0000001+0000')
Timestamp('2013-01-01 00:00:00+0000', tz='UTC')

>>> pd.Timestamp('20130101T000000.00000001+0000')
Timestamp('2013-01-01 00:00:00+0000', tz='UTC')
```
The behavior seems correct when using a different string format:
```python
>>> pd.Timestamp('2013-01-01 00:00:00.00000001+0000')
Timestamp('2013-01-01 00:00:00.000000010+0000', tz='UTC')
```
Using pandas 0.16.0, python 2.7.6

**Comment by sinhrks** [comment]
Because dateutil doesn't support nanosecond, it looks little difficult to cover all the cases to nanoseconds (see #7905).
 
One option is to prepare a parser to support some popular date formats. For example, change (or prepare separate function like) ``np_datetime_string.c`` to allow formats other separators or without separators (like suggested in #9714).

A PR would be appreciated :)
