### ISSUE TITLE
potential dataframe apply bug

### ISSUE THREAD

**Issue by michaelaye** [pydata/pandas#10399]
I seem to have a weird problem with DataFrame.apply(.., axis=1) not matching the axes/columns correctly, ONLY if there's a time column in the dataframe?
See details here: http://nbviewer.ipython.org/gist/anonymous/a0bcaa95a48327fadc63

but basically I try to apply this:

```python
def combine_binning_data(row):
    return tuple(int(row[col]) for col in [0,1,2])
```
to the dataframe.And if there's another axis with time I get this error:

```python
ValueError: Shape of passed values is (5, 3), indices imply (5, 5)
```

Version: '0.16.2-15-g2fea54a'

**Comment by jreback** [comment]
You probably want something like this.
```
In [41]: np.rint(df.loc[:,[0,1,2,3]])
Out[41]: 
   0  1  2  3
0  0  2 -1  1
1 -1  0  0 -2
2  1  1 -2  1
3  0  2  1 -0
4  0 -2 -1  2
```

If you defined like this would works as well (but would be generally slower than the above)
```
In [44]: def combine_binning_data2(row):
    return Series(int(row[col]) for col in [0,1,2,3])
   ....: 

In [46]: df.apply(combine_binning_data2,axis=1)
Out[46]: 
   0  1  2  3
0  0  1 -1  1
1  0  0  0 -1
2  0  0 -1  1
3  0  1  1  0
4  0 -2  0  1
```
You are returning a tuple from the apply, which is then interpreted as a Series. Not sure how otherwise would be able to infer the correct results here. Not a bug, rather an ambiguous return from an apply.

**Comment by michaelaye** [comment]
But why does it suddenly work when I just make the timeseries the index of the dataframe? (see last cell in the linked notebook).
