### ISSUE TITLE
Subclassed attributes are not serializable

### ISSUE THREAD

**Issue by kjordahl** [pydata/pandas#10553]
In a subclass of pandas objects, pickling an object doesn't serialize properties of an instance of that subclass, even if the attribute has been added to `_metadata`. It would be hard to override this behavior entirely in the subclass, because it will require updates to `__getstate__` and `__setstate__`, and probably also an addition or subclass of `BlockManager`. It would be nice if the `_metadata` serialization was handled in the base pandas class.

Example:

    class SubDataFrame(DataFrame):

        _metadata = ['my_data']

        @property
        def _constructor(self):
            return SubDataFrame

    sdf = SubDataFrame()
    sdf.my_data = 'foo'
    sdf.to_pickle('tmp.pkl')
    new_sdf = read_pickle('tmp.pkl')
    new_sdf.my_data

raises `AttributeError: 'SubDataFrame' object has no attribute 'my_data'`

(edited original example for correctness)

**Comment by jreback** [comment]
I think if this were replaces ``core/generic.py`` (and no need to have the ``Series.__getstate__`` either)
then this would work (and be back-compat). The reconstruction accepts a dict of these things
```
 def __getstate__(self):
        meta = dict([ (k, getattr(self, k, None)) for k in self._metadata ])
        return dict(_data=self._data, **meta)
```

Want to do a pull-request (already lots of tests on prior version pickle recovery in ``pandas/io/tests/test_pickle.py`` so that will test the back-compat)

**Comment by kjordahl** [comment]
@jreback Thanks, that's simpler than I thought. I had to add a couple more attributes (`_metadata` and `_typ`) to make sure it gets deserialized. #10557 submitted.
