### ISSUE TITLE
Pandas 'unstack' returns a Series instead of a Dataframe?

### ISSUE THREAD

**Issue by dbl001** [pydata/pandas#10584]
What causes Pandas 'unstack' to output a series instead of a Dataframe?

import pandas as pd;

events = pd.DataFrame.from_csv('/Users/davidlaxer/gdelt/events/20150613.export.CSV', sep='\t', index_col='GLOBALEVENTID')

e = events.unstack()
type(e)

Out[129]:
pandas.core.series.Series

**Comment by TomAugspurger** [comment]
Can you provide a reproducible example? We don't have access to that csv.
It's probably because `events` doesn't have a `MultiIndex`, since you just give it one column `GLOBALEVENTID`.

Does this give the same behavior?

```pytthon
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
type(df.unstack())
```

From the doctstring:

Signature: pd.DataFrame.unstack(self, level=-1)
Docstring:
Pivot a level of the (necessarily hierarchical) index labels, returning
a DataFrame having a new level of column labels whose inner-most level
consists of the pivoted index labels. **If the index is not a MultiIndex,
the output will be a Series (the analogue of stack when the columns are
not a MultiIndex).**
The level involved will automatically get sorted.

**Comment by dbl001** [comment]
>> Does this give the same behavior?
Yes.  (see bottom of screen snapshot).

Attached is 100 lines of the file .

**Comment by TomAugspurger** [comment]
Ok, so that's it then.

I'm not entirely sure why `.unstack` with a non-MultiIndex stacks, but that's working as documented. It's been that way for a long time as far as I can tell.
