### ISSUE TITLE
df.to_json segfaults with categorical column types

### ISSUE THREAD

**Issue by blink1073** [pydata/pandas#10778]
This code from the Categorical tutorial:

```python
df = pd.DataFrame({"A":["a","b","c","a"]})
df["B"] = df["A"].astype('category')
```

Will segfault when `df.to_json` is called.  Tested on:

```bash
Python 3.4.3 |Anaconda 2.3.0 (x86_64)| (default, Mar  6 2015, 12:07:41)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
$ conda list  | grep pandas
pandas                    0.16.2               np19py34_0
```

**Comment by blink1073** [comment]
If I convert using `df['B'] = df['B'].astype(str)`, then `df.to_json` works fine.

**Comment by jreback** [comment]
xref #10321 

This has not been implemented. pull-requests are welcome.

**Comment by bbirand** [comment]
:+1:

**Comment by Timusan** [comment]
My apologies if this is simply extra noise, but I think I came across the same issue in (maybe) a slightly different situation. Thought this might help to give more insight into this issue.

With me this happens when trying to convert a DataFrame with binned data into JSON.

The kernel reports back the following:

Jan 30 18:18:04 debian kernel: [ 1632.371968] python[24794]: segfault at ffffffffffffffff ip 00007f58f570655d sp 00007ffe13a8c410 error 7 in multiarray.so[7f58f55bf000+1d9000]

Version info:

Python 2.7.10
NumPy 1.10.4
Pandas 0.17.1

Greatly simplified piece of code which reproduces the error:

```
import pandas

def calculate_age_dist(df):
    # Setup the bins to divide. Setting a final bin
    # of 200 to mimic 60+ behavior.
    age_ranges = [0,2,10,20,30,40,50,60,200]
    age_ranges_labels = ['0-1', '2-9', '10-19', '20-29',
                         '30-39', '40-49', '50-59', '60+']

    # Divide the data into the bins. Using "right=False" to
    # exclude the upper range (so 30 is only included in bin 30-40
    # and not in bin 20-30).
    df['age_cat'] = pandas.cut(x = df['age'],
                               bins = age_ranges,
                               right = False,
                               labels = age_ranges_labels)

    # Leave only the top ten sports per age group
    # and convert the whole back to a DataFrame.
    age_dist = age_dist.groupby('age_cat').head(10).reset_index(drop=True)

    return age_dist

# The data.
df = pandas.DataFrame(data = {'age': [55,20,30,40,50,60,65,23],
                              'sport': ['soccer', 'baseball', 'soccer', 'football',
                                        'swimming', 'tennig', 'swimming', 'baseball']},
                      columns = {'age', 'sport'})

# The call which causes the segfault.
print calculate_age_dist(df).to_json()
```

Converting the "age_cat" column with `df['age_cat'] = df['age_cat'].astype(str)` does indeed circumvent the segfault.

**Comment by tollycoast** [comment]
Thanks the issue have is instead to display entire data with the same criteria in the csv, only the last data of the category are displayed 

Date: Sat, 30 Jan 2016 01:27:31 -0800

**Comment by Timusan** [comment]
@tollycoast, I may be wrong, but I think your question is totally unrelated to the issue at hand.

**Comment by tollycoast** [comment]
Thank you so much for your sir
You are right sir! I only seek for assistance to fix the code. 
I have a csv file, which has several IDs, these fall in categories of arrival, departure, within range of dates. I have group by date and then find any of the IDs on particular date sharing the same place of arrival and /or departure with any other IDs

import pandas as pd
import datetime
import numpy as np
from pandas_datareader import data, wb
import csv
import json

df = pd.read_csv('testfile.csv') 
df.DepartureDate = pd.to_datetime(df.DepartureDate)
df.ArrivalDate = pd.to_datetime(df.ArrivalDate)
df = df.set_index('ArrivalDate')
new_df = pd.DataFrame()
for i, data in df.iterrows():
    data = data.to_frame().transpose()
    data = data.reindex(pd.date_range(start=data.index[0], end=data.DepartureDate[0])).fillna(method='ffill').reset_index().rename(columns={'index': 'ArrivalDate'})
    new_df = pd.concat([new_df, data])

new_df = new_df[['ID', 'Arrival', 'Departure', 'ArrivalDate', 'DepartureDate']]

print (new_df) 

json_dict = {}

for arrival_date, data in new_df.groupby('ArrivalDate'):
    matching_dates = data[data.DepartureDate==arrival_date]
    not_matching_dates = data[data.DepartureDate!=arrival_date]
    json_dict[arrival_date.strftime('%Y-%m-%d')] = {}
    if not matching_dates.empty:
        for city, flights in matching_dates.groupby('Arrival'):
            json_dict[arrival_date.strftime('%Y-%m-%d')][city] = [str(v) for v in flights.ID.to_dict().values()]
    if not not_matching_dates.empty:
        for city, flights in not_matching_dates.groupby('Departure'):
            json_dict[arrival_date.strftime('%Y-%m-%d')][city] = [str(v) for v in flights.ID.to_dict().values()]


with open('json_dict.json', 'w') as f:
     json.dump(json_dict, f, indent=4, sort_keys=True)


The desired output:

{
    "2001-02-02": {
        "Japan": [
            "CCC",
            "GGG"
        ],
        "UK": [
            "EEE"
        ],
        "UnitedState": [
            "AAA"
            "BBB"
            "DDD"
            "FFF"
        ],
        "France": [
            "AAA"
            "BBB"
            "CCC"
            "DDD"
            "EEE"
            "FFF"
        ]

    },

    .
    .
    .
  }
The current output 


{
    "2001-02-02": {
        "Japan": [
            "GGG"
        ],
        "UK": [
            "EEE"
        ],
        "UnitedState": [
            "FFF"
        ]
    },
    "2001-02-03": {
        "Japan": [
            "GGG"
        ],
        "UK": [
            "EEE"
        ],
        "UnitedState": [
            "FFF"
        ]
    },
    .
    .
    .
  }

**Comment by annacnev** [comment]
Apologies for the noise, came across this issue two weeks ago when I was converting a json file to a pandas data frame using pd.DataFrame.from_records. I had a large json file that I pulled from multiple webpages into one file that I was trying to parse through and separate using a loop and the pandas function. One of the webpages did not load and it went into my larger file as an empty list-unbeknownst to me. That empty list when read into pandas caused the seg fault. Took me forever to figure that out and eventually adding a try and except to my code solved the issue. 

Not sure if this is the appropriate place to post this, but this was the first forum that came up when I googled "seg fault json pandas" and I wanted to put this out there incase someone in future ran into the problem I had and might be able to save some time. 

One the developer site though, just a recommendation, it might be nice if a try and except could be added to the "from records" function that would give an output when an empty list is encountered because that seg fault had me messing with my python framework thinking something was very wrong.
