### ISSUE TITLE
ENH: scatter_matrix doesn't handle columns with dtype 'pd.Categorical' or any other non-numeric

### ISSUE THREAD

**Issue by soupault** [pydata/pandas#11143]
I understand that `object` dtype supporting couldn't be the right option, but it is quite feasible to implement support for `Categorical`.

Right now, all columns of 'DataFrame' which aren't numeric are dropped before visualization procedure of `scatter_matrix`.

**Comment by TomAugspurger** [comment]
Scatter plots often don't work well with categoricals, since you'll possibly end up with a overlappinig points.

Have you seen seaborn's [Pairgrid](http://stanford.edu/~mwaskom/software/seaborn/tutorial/axis_grids.html#plotting-pairwise-relationships-with-pairgrid-and-pairplot)? You're probably better off using that and splitting your categorical by hue.

**Comment by soupault** [comment]
Thanks for the link, Tom! To be honest, in my task there are several `Categorical`'s, so both approaches have own pro's and con's.
I just wonder if is it in `Pandas` interest to maintain existing visualization tools.

**Comment by TomAugspurger** [comment]
With several categoricals, things are even harder. A scatter plot of categorical vs. categorical would just have (at most) 1 point per pair. In these case's I'll usually facet by the categorial with seaborn's FacetGrid.

> I just wonder if is it in Pandas interest to maintain existing visualization tools.

Maintain yes, but no plans to expand them. Libraries like seaborn do a better job.

**Comment by soupault** [comment]
OK, clear!
Thank you for the directions, Tom!
