### ISSUE TITLE
add a graph data structure using the data frame

### ISSUE THREAD

**Issue by annamcmahon** [pydata/pandas#11236]

**Comment by jreback** [comment]
an example of the case would be helpful

**Comment by annamcmahon** [comment]
This is useful for visualize or analyze the relationship and connections between data points. For example, it would be useful for analyzing/visualizing social relationships

**Comment by jreback** [comment]
can u give a pseudo code example , eg show a sample input and then a sample of what the analysis would look like

**Comment by cindyxinyiwang** [comment]
Maybe we could have a input file that specifies the entries that a certain entry is connected. Say we have a table:
        Name      Children
0       a               (2, 3)
1       ab              ()
2       e                (1, 3)
3       f                 (0, 1)

so entry 0 is connected to entry 2 and 3, entry 2 is connected to entry 1 and 3 etc. Maybe we should use a unique id/address instead of the index as an identifier for children

**Comment by TomAugspurger** [comment]
Typically this is done with either [networkx](https://networkx.github.io/) for very flexible graphs, or something like a scipy sparse matrix for more representing regular graphs like an Adjacency matrix.

I don't think anything in pandas codebase lends itself to graph operations / analysis. pandas is more for tabular data.
