### ISSUE TITLE
pandas.Series.__eq__ is broken for series with different index

### ISSUE THREAD

**Issue by lesteve** [pydata/pandas#1134]
Something seems to be wrong with s1 == s2 when s1 and s2 don't have the same index. Here is a snippet example:

```python
import operator
import pandas
s1 = pandas.Series([1,2], ['a','b'])
s2 = pandas.Series([2,3], ['b','c'])
s1 == s2
s2 == s1
```
with the output:
```
InIn [5]: s1 == s2
Out[5]: 
a    False
b    False

In [6]: s2 == s1
Out[6]: 
b    False
c    False
```

On the other hand using combine works fine:
```
In [7]: s1.combine(s2, operator.eq)
Out[7]: 
a    0
b    1
c    0

In [8]: s2.combine(s1, operator.eq)
Out[8]: 
a    0
b    1
c    0
```

I guess you can first align s1 and s2 and then compare them, but is there a good reason why this couldn't work out of the box?

There doesn't seem to be any tests for pandas.Series. \_\_eq\_\_ for two series with a different index in pandas/pandas/tests/test_series.py. I have a patch lying around to add such a test and I could commit it if that's useful.

**Comment by jreback** [comment]
reported here again: http://stackoverflow.com/questions/30284415/why-do-pandas-comparison-operators-not-align-on-index/30285686#30285686

**Comment by wesm** [comment]
Bumping this issue

**Comment by sinhrks** [comment]
+1 on adding flexible methods. 

Also, there are inconsistencies in normal ops between ``Series`` and ``DataFrame`` as @jorisvandenbossche pointed. I`ve organized the differences including arithmetic / bool op (xref: #7278, .#13538, #13587)

## Series 

### Arithmetic

aligns with labels.

```
pd.Series([1, 2, 3], index=list('ABC')) + pd.Series([2, 2, 2], index=list('ABD')) 
# A    3.0
# B    4.0
# C    NaN
# D    NaN
# dtype: float64

# pd.Series([1, 2, 3], index=list('ABC')) + pd.Series([2, 2, 2, 2], index=list('ABCD')) 
# A    3.0
# B    4.0
# C    5.0
# D    NaN
# dtype: float64
```

## Comparison

ignores labels, raises when lengths are different.

```
pd.Series([1, 2, 3], index=list('ABC')) > pd.Series([2, 2, 2], index=list('ABD')) 
# A    False
# B    False
# C     True
# dtype: bool

pd.Series([1, 2, 3], index=list('ABC')) > pd.Series([2, 2, 2, 2], index=list('ABCD'))
# ValueError: Series lengths must match to compare
```

## Boolean (logical)

ignores labels, ignores length mismatch.

```
pd.Series([True, False, True], index=list('ABC')) & pd.Series([True, True, True], index=list('ABD'))
# A     True
# B    False
# C    False
# dtype: bool

pd.Series([True, False, True], index=list('ABC')) & pd.Series([True, True, True, True], index=list('ABCD'))
# A     True
# B    False
# C     True
# dtype: bool
```

## DataFrame

### Arithmetic

aligns with labels.

```
pd.DataFrame([1, 2, 3], index=list('ABC')) + pd.DataFrame([2, 2, 2], index=list('ABD'))
#      0
# A  3.0
# B  4.0
# C  NaN
# D  NaN

pd.DataFrame([1, 2, 3], index=list('ABC')) + pd.DataFrame([2, 2, 2, 2], index=list('ABCD')) 
#      0
# A  3.0
# B  4.0
# C  5.0
# D  NaN
```

## Comparison

raises when labels are different.

```
pd.DataFrame([1, 2, 3], index=list('ABC')) > pd.DataFrame([2, 2, 2], index=list('ABD'))
# ValueError: Can only compare identically-labeled DataFrame objects

pd.DataFrame([1, 2, 3], index=list('ABC')) > pd.DataFrame([2, 2, 2, 2], index=list('ABCD'))
# ValueError: Can only compare identically-labeled DataFrame objects
```

## Boolean (logical)

aligns with labels.

```
pd.DataFrame([True, False, True], index=list('ABC')) & pd.DataFrame([True, True, True], index=list('ABD')) 
#        0
# A   True
# B  False
# C    NaN
# D    NaN

pd.DataFrame([True, False, True], index=list('ABC')) & pd.DataFrame([True, True, True, True], index=list('ABCD'))
#        0
# A   True
# B  False
# C    NaN
# D    NaN
```

Based on above, I think followings are consistent:

- arithmetic always align with labels
- comparison is allowed when labels are identical. otherwise raises.
- boolean always align with labels

If OK, I'd like to do 2 changes:

- series comparison to check whether labels are identical
- series boolean to align with labels
