### ISSUE TITLE
read_csv skiprows not always 0-indexed

### ISSUE THREAD

**Issue by joristork** [pydata/pandas#11508]
Indexing is inconsistent in Pandas v.0.16.2 `read_csv`'s `skiprows` option. For example:
Given the csv `temp.txt`:
```
a,b,c
1,2,3
4,5,6
7,8,9
```

this happens:
```
In [76]: pd.read_csv('temp.txt', dtype=str, skiprows=[1,2])
Out[76]: 
   a  b  c
0  7  8  9

In [77]: pd.read_csv('temp.txt', dtype=str, skiprows=[0,1])
Out[77]: 
   4  5  6
0  7  8  9
```

whereas the documentation says:
```
skiprows : list-like or integer
    Line numbers to skip (0-indexed) or number of lines to skip (int)
    at the start of the file
```

**Comment by joristork** [comment]
My bad, it is 0-indexed and includes the csv header in that.

**Comment by brendanq3** [comment]
Following up on this though, this presents an annoying issue if you do want to exclude rows based on what the index would look like when run through read_csv (so that the first non-header row is indexed 0).

We had a process in which we had to upload a few columns from a CSV to THEN determine which rows from the same CSV we wanted all columns for.

The solution we had to use was:

```
import pandas as pd

df_initial = pd.read_csv('example_csv', delimiter=',', header=0)

# Code to figure out that the rows we wanted to skip were indexed 0, 3, 5, 7, ...

rows_to_skip = [0,3,5,7,...]

df = pd.read_csv('example_csv', delimiter=',', header=0, skiprows=[x+1 for x in rows_to_skip])
```

Is there an easier way to do this, or can the skiprows be updated to re-index if header=0 is specified?
