### ISSUE TITLE
Install.rst is missing references to optional packages

### ISSUE THREAD

**Issue by jlec** [pydata/pandas#11686]
Following references are missing

* rpy2
* psycopg (at least testing needs it)
* pymysql (at least testing needs it)
* matplotlib

perhaps there are more.

**Comment by jorisvandenbossche** [comment]
Thanks for the report!

``matplotlib`` is mentioned (http://pandas.pydata.org/pandas-docs/stable/install.html#optional-dependencies), ``rpy2`` is for a deprecated module, so I don't think it is worth to add it. 
For `psycopg2` and `pymysql`, I think we can add these as 'examples' of database drivers that you need together with sqlalchemy (because there are many more possibilities to install).

**Comment by jlec** [comment]
I overlooked ```matplotlib```. 

Regarding rpy I read the docs as if the ```pandas.rpy```module is deprecated but you can/should use rpy2 to interface with R.

**Comment by jorisvandenbossche** [comment]
On rpy2, you are correct that it is `pandas.rpy` that is deprecated, but for pandas itself, `rpy2` is only needed for that module. You can of course use more in general `rpy2` to interface with R, but I don't think this should be included in the 'install' part for pandas (we cannot add every library that can be used together with pandas, therefore there is eg the ecosystem page in the docs).
