### ISSUE TITLE
Series.ptp function does not correctly use axis='index' argument

### ISSUE THREAD

**Issue by kesyog** [pydata/pandas#11753]
When using [Series.ptp()](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.ptp.html?highlight=ptp#pandas.Series.ptp) with `axis='index'` as an argument, I would expect the function to return max(index) - min(index). Instead, it appears as if the operation is performed on the data held in the Series (as if the `axis='index'` argument were not provided at all).

    x = pd.Series(np.linspace(0,5,6)*2, index=np.linspace(0,5,6))
    print x.ptp() #expect 10, get 10
    print x.ptp(axis=0) #expect 10, get 10
    print x.ptp(axis='index') #expect 5, get 10
    print x.index.max()-x.index.min() #expect 5, get 5

I'm using Pandas 0.17.1.

**Comment by rockg** [comment]
I think there is a misunderstanding here.  `axis='index'` and `axis=0` are the same thing, just synonyms for the dimension to do the operation on.  And actually for series having the `axis` argument does not make any sense since it is a 1-dimensional object.  If you want to do it on the index itself, you need to make that a column in a DataFrame.
