### ISSUE TITLE
MultiIndex methods not listed in API reference

### ISSUE THREAD

**Issue by Dr-Irv** [pydata/pandas#11890]
It would be really useful to have the documentation for the methods specific to `MultiIndex` such as `.from_product()` and `.from_tuples()` to be listed with links in the API reference (http://pandas.pydata.org/pandas-docs/stable/api.html). 

I'm willing to edit the api.rst file, but when I build the docs from scratch (using `python make.py html`), the resulting api.html file is incomplete.  Before I make changes, I'd like to make sure the build of the docs works right.  Maybe the build issue should be a different issue?

**Comment by jorisvandenbossche** [comment]
I think it would certainly be good to add these to the api.rst page.

About the doc building, what do you exactly mean with 'incomplete'? If you don't have a specific issue that can be reported, but like more general help, it can also be easier to use the gitter channel to help you instead of github issues -> https://gitter.im/pydata/pandas

**Comment by Dr-Irv** [comment]
For later reference, the doc building issue was that I was using Sphinx 1.3.1.  Using Sphinx 1.3.3 fixed the problem.  Now I will update the api.rst page.

**Comment by jreback** [comment]
@jorisvandenbossche xref to #11893
