### ISSUE TITLE
install pandas :unable to find vcavarsall.bat

### ISSUE THREAD

**Issue by jhlpotato** [pydata/pandas#12024]
python 3.0+
window microsoft visual studio 2008 and 2010 both install

**Comment by TomAugspurger** [comment]
Are you sure you're using python 3.0? and not, say 3.4 or higher?

On window typically recommend using [conda](http://pandas.pydata.org/pandas-docs/version/0.17.1/install.html#installing-pandas-with-anaconda) to avoid these issues. Otherwise Christoph Gohlke provides a bunch of [wheels](http://www.lfd.uci.edu/~gohlke/pythonlibs/)
