### ISSUE TITLE
BUG: _repr_latex is called in jupyter qtconsole

### ISSUE THREAD

**Issue by chris-b1** [pydata/pandas#12182]
xref #11778

![image](https://cloud.githubusercontent.com/assets/1924092/12692982/4ff32128-c6c5-11e5-8ca4-14750f904a8f.png)

**Comment by jreback** [comment]
hmm, is this on master?

**Comment by jorisvandenbossche** [comment]
There are some issues at IPython/Jupyter for this: https://github.com/jupyter/qtconsole/pull/65, https://github.com/jupyter/qtconsole/issues/56 (IRkernel has the same problem for the display of their dataframes)

@chris-b1 Would you be able to test if this is solved in qtconsole master?

**Comment by jorisvandenbossche** [comment]
I think this is a reason to *consider* reverting #11778

**Comment by jreback** [comment]
cc @nbonnotte

**Comment by tollycoast** [comment]
Yes sir 
Date: Sat, 30 Jan 2016 06:48:21 -0800

**Comment by jorisvandenbossche** [comment]
Or, another option is making the use of the `_repr_latex_` optional, and defaulting to False. So somebody who wants this feature for nbconvert, can switch it on, but knowing that it will bug in qtconsole.

**Comment by jreback** [comment]
so we could have an option ``display.latex.repr=False`` maybe?

**Comment by chris-b1** [comment]
Yeah, this also happens on qtconsole master.  If there was a way to make this [`in_qtconsole`](https://github.com/pydata/pandas/blob/master/pandas/core/common.py#L2743) check work again, that'd be a way to avoid an option.

But since they've restructured all the ipython/jupyter stuff, I don't know how (if it's possible) to do that.

**Comment by nbonnotte** [comment]
This goes beyond my current use of pandas or jupyter, so I'm not really qualified to say anything.

That being said, I like the idea of being able to nicely export my notebooks containing dataframes to LaTeX. And, if I understand correctly, this is more a bug of the jupyter qtconsole rather than pandas, right? So, if anything, my current understanding of the situation does not convince me that reverting #11778 is absolutely necessary. But maybe it's just because I use jupyter notebooks, and I feel closer to exporting them to LaTeX rather than using the qtconsole.

**Comment by jorisvandenbossche** [comment]
> And, if I understand correctly, this is more a bug of the jupyter qtconsole rather than pandas, right? So, if anything, my current understanding of the situation does not convince me that reverting #11778 is absolutely necessary. But maybe it's just because I use jupyter notebooks

The qtconsole is used in eg Spyder, which I suppose quite some pandas users will use. 
To be clear, ideally we find another solution or workaround so reverting #11778 is not needed. But if not, we cannot ship pandas like this in any case, as it would break the interactive usage for lots of users.

**Comment by jorisvandenbossche** [comment]
A possible idea is to do something similar as what `sympy` does, so that the user has to call a function to activate the latex repr support (`sympy.init_printing()`). 
E.g. a `pd.options.display.init_latex_repr()` (although this being a function is not really consistent with the other options). Calling the function would then add the `_repr_latex_` method to DataFrame on the fly.

**Comment by nbonnotte** [comment]
Would it still be possible to convert a notebook to LaTeX?

And a naive question: what prevents [in_qtconsole](https://github.com/pydata/pandas/blob/fc77cafe2a70cc08a81ebf2e855bca096f3bb7e6/pandas/core/common.py#L2765-L2780) from working? Is it because jupyter does not want us to know to which front-end it is connected?

**Comment by jorisvandenbossche** [comment]
> Would it still be possible to convert a notebook to LaTeX?

Yes, but you will just have call this function in the beginning of your notebook that you want to convert to latex to activate the latex repr

> And a naive question: what prevents in_qtconsole from working? Is it because jupyter does not want us to know to which front-end it is connected?

As far as I understand, yes, the kernel does not know in which frontend it is run (notebook or qtconsole or ... are all `ipykernel.zmqshell.ZMQInteractiveShell` ). And if you want to convert a notebook to nbconvert, the latex repr should already be stored inside of the notebook.

**Comment by jreback** [comment]
@jorisvandenbossche so what should we do about this, revert the actual ``_repr_latex_`` method?

The other changes are fine.

**Comment by jorisvandenbossche** [comment]
I think the best would be something like the following:

Have a new `pd.options.display.latex_repr` option, which defaults to False, and when setting it to True, this triggers a callback function that adds the `_latex_repr_` method dynamically to DataFrame.

**Comment by chris-b1** [comment]
It doesn't even need to be a callback, `_repr_latex` can just return `None` (if the option is False) and the qtconsole will fallback.  I'll submit a PR here shortly.

**Comment by jorisvandenbossche** [comment]
Ah, yes, that seems also to work. Even simpler!
