### ISSUE TITLE
Helper class to keep enable autocomplete of the columns in notebooks

### ISSUE THREAD

**Issue by rsdenijs** [pydata/pandas#12280]
When working on the notebook I am always annoyed that column names do not autocomplete in all scenarios. 

`dataframe = pd.DataFrame({'COL1':[1,2,3],'COL2':[2,3,4]})`

When typing 
`dataframe['CO       <--- The notebook will suggest COL1 and COL2 when pressing TAB`

but im lost when using

`pd.pivot_table(index='CO   <--- No chance`

My workaround is the following class, which creates an object that binds itself to a given DataFrame and keeps track of the columns

```
class Columns:
    import threading
    def __init__(self, df):
        self._df = df
        self._update()
        
    def _update(self):        
        self.__dict__.update({d:d for d in self._df.columns.tolist()})
        threading.Timer(3, self._update).start()

```

So now i use the object to autocomplete columns

```
C= Columns(dataframe)

pd.pivot_table(index=C.CO   <--- Yay! Autocomplete works again

```

Do you know of any better solution? And if not... maybe something like this can be included out-of-the-box in pandas for notebook users?

**Comment by TomAugspurger** [comment]
Your specific case might be hard since `pd.pivot_table` is a top-level function, so pretty much anything could go into those arguments.

OTOH something like `pd.DataFrame.pivot_table` might benefit from a richer tab complete protocol since the suggestions for `DataFrame.piviot_table(index=...)` could come from `self.index`. I've looked a bit into  what IPython can offer here, but haven't found much. Would be curious to see if you find anything.

**Comment by minrk** [comment]
There isn't a hook in IPython for selecting completions specially based on the function or kwarg being completed-for. But for completing *on* objects, `__dir__` is used, so your Columns workaround can at least avoid its thread:

```python
class Columns:
    def __init__(self, df):
        self._df = df
    
    def __dir__(self):
        return self._df.columns.tolist()
    
    def __getattr__(self, key):
        if key not in self._df.columns:
            raise AttributeError(key)
        return key
```

Even if there were a way for `pivot_table` to say "look at column names of DataFrames", where to find those data frames would be the next hurdle. If it were a method, there's more hope that custom kwarg-complete hook could help, but that doesn't exist, yet.

**Comment by rsdenijs** [comment]
@minrk  thanks for getting rid of the thread ;). 
So shouldnt `df.pivot_table` as @TomAugspurger  mentions be able to use the autocompletion? Or is it not possible because  `pivot_table` is a method and not an object itself?

Another workaround is pd.pivot_table(index=df.COL1.name... etc) but it is longer and requires 2 tab completions

**Comment by TomAugspurger** [comment]
Right now tab completion on the arguments to a function look up objects in the global namespace (plus maybe some other things like paths?). Since the index labels aren't in the namespace they aren't available for tab completion.

In principle letting the method say "Hey, I know the argument to `index=` should come from `self.index`" is possible, but would require (I'm guessing) a lot of work on the Jupyter and IPython kernel side.

**Comment by minrk** [comment]
> but would require (I'm guessing) a lot of work on the Jupyter and IPython kernel side

Not necessarily a lot, but some. We already find the callable in order to get completion on the keywords:

```python
df.pivot_table(ind<tab> -> df.pivot_table(index=)
```

which means we should already have a handle on the method and the key. So what's missing is a hook for "I know I'm completing a kwarg *value*, ask the callable what it should be." I'm not sure what would be a sensible way to ask that question, though. The obvious choice is a `_ip_complete_kwarg_(keyword)` method on the callable, but that would be a method on the *pivot_table method*, which is pretty weird.

**Comment by TomAugspurger** [comment]
That's where my mind was going, or some kind of decorator that attaches the relevant completion method to the original method.

```pytohn
@_ipy_complete_kwarg(index, options=lambda self: self.index.tolist())
@_ipy_complete_kwarg(columns, options=lambda self: self.columns.tolist())
def pivot_table(self, index, ...):
   ...
```

Adding that those to a codebsae would be fun :)

Anyway, something like this would be *nice* for libraries like pandas that are used interactively, but IMO it's not a essential.

**Comment by MaximilianR** [comment]
One option in this case - less flexible, but much less code - define a method on `index`, so `df.method(index= <tab>` calls in to `df.index` to get a list of options. That could be defined on any attribute of `df`; i.e. `df.method(foo= <tab>` calls `df.foo. _ipy_complete_kwarg()` or the like.

**Comment by TomAugspurger** [comment]
One issue with that is something like `DataFrame.rename(index=...)` has a different set of allowed arguments then `DataFrame.pivot_table(index=...)`. Tricky problem.

**Comment by MaximilianR** [comment]
>One issue with that is something like DataFrame.rename(index=...) has a different set of allowed arguments then DataFrame.pivot_table(index=...). Tricky problem.

Ah, good point.

Type annotations could help here...

**Comment by rsdenijs** [comment]
> Adding those to a codebsae would be fun :)

Cant this be a something run only on interactive mode? Monkeypatch? ^^

Btw` @_ipy_complete_kwarg(index, options=lambda self: self.index.tolist())` seems wrong to me, as i can put any column in the index, not just the values of the index.
