### ISSUE TITLE
COMPAT: breakage with just merged: https://github.com/numpy/numpy/pull/7325

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#12687]
see [here](https://travis-ci.org/pydata/pandas/jobs/117710492)
xref #12603 
#12644 

[numpy issue 7325](https://github.com/numpy/numpy/pull/7325)

cc @gfyoung 
cc @njsmith

**Comment by jreback** [comment]
@gfyoung I think we just need to *also* accept ``**kwargs`` (and validate)

**Comment by gfyoung** [comment]
@jreback : The test needs to be modified to check which version of `numpy` we are using.  That exception will only be thrown if we're not using `nump-dev` (on `numpy-dev`, no exceptions will be thrown because the `DataFrame` or `Series` gets converted to a `numpy` array).  What's the best the way to check `numpy` version?

**Comment by jreback** [comment]
I don't think its a test failure, rather need to accept ``**kwargs`` AS WELL as ``*args`` (similar to how we do in the stat functions). The signature is consistent across all versions of numpy. I don't want to see specific version tests, except in very specific cases.

```
In [1]: pd.Series.round?
Signature: pd.Series.round(self, decimals=0, *args)
``

**Comment by gfyoung** [comment]
Fair enough.  I'll tackle this issue in a PR that will also fix #12644.

**Comment by jreback** [comment]
@gfyoung if you have a chance on this one. annoying when master fails :< (even though its the allowed failures, that's just to make it finish faster :)

**Comment by gfyoung** [comment]
@jreback : No worries.  As I said above, I'll fix it in a PR that will all of the `fromnumeric.py` compat issues.

**Comment by jreback** [comment]
@gfyoung ok, great.

**Comment by jreback** [comment]
@gfyoung if you are looking for something to do.....I want to fix the failing build on travis (numpy compat build) for this (can leave open for more general things).

**Comment by gfyoung** [comment]
@jreback : Alas, the fix is more complicated than just adding `**kwargs`.  I didn't consider the fact that a function can raise `TypeError` that isn't necessarily a signature compatibility issue, like when you try to take the sum of a `Series` with `Categorical` data.

xref <a href="https://github.com/numpy/numpy/pull/7491">#7491</a> in `numpy`

**Comment by gfyoung** [comment]
My massive PR #12810 will address this breakage on the `pandas` side now.  The combination of my `numpy` PR and this one should fully fix the problem.

**Comment by charris** [comment]
Does this fix the pandas breakage without any work on the pandas side? I'm somewhat annoyed that there was a problem.
