### ISSUE TITLE
RangeIndex not generated with pd.concat with ignore_index as True

### ISSUE THREAD

**Issue by AnkurDedania** [pydata/pandas#12695]
With version 0.18.0 introducing RangeIndex, should RangeIndex be applied for concat when ignore_index is set to True?

``df = pd.concat([df_a, df_b], ignore_index=True)``

df.index is an instance of Int64Index, not RangeIndex currently in 0.18.0

**Comment by jreback** [comment]
yes this should be here as well. pull-requests welcome.

**Comment by jreback** [comment]
make sure tests are of the form: ``assert_frame_equal(resut, expected, check_index_type=True)`` (otherwise defaults to an 'equiv' comparison, which doesnt distinguish between Int64 and equiv RangeIndex.

In fact that is how to find differences in the test suite (to look for cases where we could/should be returning a ``RangeIndex`` but are currently not).
