### ISSUE TITLE
BUG: Resample on empty Period-Indexed Series returns Datetime-Indexed Series

### ISSUE THREAD

**Issue by jduncavage** [pydata/pandas#12868]
#### Code Sample, a copy-pastable example if possible
`
In [7]: pd.Series([], pd.period_range(start='2000', periods=0)).resample('W').mean().index
Out[7]: DatetimeIndex([], dtype='datetime64[ns]', freq='W-SUN')
`

#### Expected Output
``
PeriodIndex([], dtype='int64', freq='W-SUN')
``

On pandas: 0.18.0

**Comment by MaximilianR** [comment]
@jreback Lots of issues with PeriodIndex & resample. ref: https://github.com/pydata/pandas/issues/12774 & ERR: Resample pad on existing freq causes recursion error 

I didn't really follow the resample refactor so I don't know the genesis of these. I had a look through the code but can't find easy fixes. Looks like a lot is reliant on the `kind` attribute, but it's not completely consistent (i.e. a resampled PeriodIndex at times changes `kind` from `period` to `timestamp`, etc).

Do you have any ideas for an overarching strategy for these? 
For example, should we just convert every `PeriodIndex` to a `DatetimeIndex`, resample it, and then convert back?

**Comment by jreback** [comment]
@MaximilianR I commented on this in #12774 . The logic from < 0.18.0 is exactly the same. The problem is the period is not systematically tested and there are quite a few edge cases. Further compounding this is the ``kind`` kw, which I think we could just totally eliminate. Now the obstacle is that its often easier to change the DTI to a PI, resample then change it back. The code paths are there, just the ``kind`` thing really perverts the logic.

So what we need is a fair amount of systematic testing. Then remove the ``kind`` (well you don't actually remove it, but deprecate it and we'll remove it later).

**Comment by jreback** [comment]
I'll make a master Period Resample issue I think.

**Comment by MaximilianR** [comment]
>Now the obstacle is that its often easier to change the DTI to a PI, resample then change it back.

OK - can I confirm that you think this is the best path forward, for all PeriodIndex resampling?

>The logic from < 0.18.0 is exactly the same. 

OK, these are regressions though (from our unit tests failing on our upgrade)

**Comment by jreback** [comment]
if u have failing tests then they must be things that are not tested in pandas - nothing regressed AFAICT
