### ISSUE TITLE
Followup to #13358 asof-join

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#13469]
xref #13358 

- [ ] need full signature on deprecated ``ordered_merge``
- [ ] ``pd.merge_asof()`` for asof-style time-series joining, see :ref:`here <whatsnew_0182.enhancements.asof_merge>` for highlites

**Comment by jreback** [comment]
closed by https://github.com/pydata/pandas/commit/013c2ce760083e5454552ad44bba8d2f44da2caa

**Comment by jreback** [comment]
@jorisvandenbossche 

In merging.rst

I don't understand why there are blank lines between the args for ``pd.merge``, but not for ``pd.concat``

They look exactly the same to me.

**Comment by jreback** [comment]
https://github.com/pydata/pandas/commit/013c2ce760083e5454552ad44bba8d2f44da2caa

**Comment by jorisvandenbossche** [comment]
I think it is because of the `.. versionadded:: 0.17.0` that is after 'indicator' kwarg for merge. Because of that there is a blank line within that bullet point, leading to sphinx to use more spacing between all  bullet points of that list. 
So maybe just add the "New in version 0.17.0." as plain text there without needing a blank line.
