### ISSUE TITLE
Support converters across multiple Excel spreadsheets

### ISSUE THREAD

**Issue by slnovak** [pydata/pandas#13545]
Hi,

When using `pd.read_excel(..., sheetname=None, converters={...})` to load all data in an Excel workbook, the columns specified in `converters` gets applied to any matching column names across _all_ spreadsheets. I have a use case where I would like to use different converter functions for columns of the same name across multiple sheets.

One potential implementation could yield:

```python
pd.read_excel("my_data.xlsx", sheetname=None, converters={
  "Sheet1": { "my_column": do_something },
  "Sheet2": { "my_column": do_something_else }})
```

Another implementation could be:

```python
pd.read_excel("my_data.xlsx", sheetname=None, converters={
  ("Sheet1", "my_column"): do_something,
  ("Sheet2", "my_column"): do_something_else })
```

Thanks! Please let me know if I can help out with an implementation -- I'd love to contribute to Pandas!

**Comment by sinhrks** [comment]
Thanks for the request. ``sheetname=None`` should be used if the option can be applied to all the sheets. Otherwise, using ``read_excel`` per sheet is better.

To cover latter case, only changing ``converter`` isn't enough because the sheet can have other differences like names, headers, etc. Making most of all the options to support ``dict`` input makes API too complex.

**Comment by slnovak** [comment]
Ah -- good point on using `read_excel` per sheet. I'm happy with closing the issue for now.

Thanks!

**Comment by sinhrks** [comment]
Thx for checking. Closing.
