### ISSUE TITLE
BUG: to_timedelta still raises with errors='ignore'

### ISSUE THREAD

**Issue by jorisvandenbossche** [pydata/pandas#13613]
From the added docs in https://github.com/pydata/pandas/pull/13425:

```
In [10]: pd.to_timedelta(['apple', '1 day'], errors='ignore')
...
ValueError: unit abbreviation w/o a number

In [12]: pd.to_timedelta(['apple', pd.Timedelta('1day')], errors='ignore')
...
ValueError: unit abbreviation w/o a number
```

It's the same error as you get with `errors='raise'` (so not captured somewhere), `errors='coerce` is working correctly.

**Comment by gfyoung** [comment]
The reason is because `errors='ignore'`, is well, ignored.  I think I would just wrap the current `try-except` logic as follows:

~~~python
try:
    try:
        for i in range(n):
            result[i] = parse_timedelta_string(values[i])  # always raise
    except Exception:
        for i in range(n):
            result[i] = convert_to_timedelta64(values[i], unit, is_coerce)
except Exception:  # when is_coerce=False
    if errors == 'raise':
        raise
   elif errors == 'ignore':
        return values
return iresult
~~~
The reason is that one could consider the original `try-except` block as the process through which we convert to `timedelta`, then all three options for `errors` are satisfied:

1) `errors='raise'`

Try to convert via method 1, which fails, so we try with method 2.  If that fails, we raise the exception.

2) `errors='coerce'` --> `is_coerce=True`

Try to convert via method 1, which fails, so we try with method 2.  In method 2, if converting one of the elements fails, we return `NPY_NAT`.

3) `errors='ignore'`

Try to convert via method 1, which fails, so we try with method 2.  If that fails, we just return the original `values` array as promised in documentation.

**Comment by jorisvandenbossche** [comment]
@gfyoung sounds good

**Comment by jreback** [comment]
yeah this prob needs some logic like that

this is similar to how datetime parsing works
