### ISSUE TITLE
BUG: resolvers in pandas.eval should accept list-like

### ISSUE THREAD

**Issue by sdementen** [pydata/pandas#14095]
I think the resolvers argument of pandas.eval requires a tuple and not a list
```
resolvers : list of dict-like or None, optional
A list of objects implementing the __getitem__ special method that you can use to inject an additional collection of namespaces to use for variable lookup. For example, this is used in the query() method to inject the index and columns variables that refer to their respective DataFrame instance attributes.
```
as with a list I get a
```
    kwargs['resolvers'] = kwargs.get('resolvers', ()) + resolvers
TypeError: can only concatenate tuple (not "list") to tuple
```

**Comment by chris-b1** [comment]
Yes, although rather than changing the docs, it should be pretty straightforward to convert any list-like into a tuple.

Probably [here](https://github.com/pydata/pandas/blob/042b6f00ad691345812e61bb7e86e52476805602/pandas/core/frame.py#L2269) and somewhere around [here](https://github.com/pydata/pandas/blob/042b6f00ad691345812e61bb7e86e52476805602/pandas/computation/eval.py#L250)

**Comment by jreback** [comment]
note that this is in reality a 'private'-ish kw, not sure what an outside of pandas user would do with it.

**Comment by sdementen** [comment]
For the use case, I use it to transform timeseries according to expressions given by the user and I want to add some "variables" that are columns of specific dataframes  (a bit like the query method)

**Comment by theultimatecrouton** [comment]
I'll have a look at fixing
