### ISSUE TITLE
DOC: source links in API reference

### ISSUE THREAD

**Issue by chris-b1** [pydata/pandas#14178]
For example, from numpy.
http://docs.scipy.org/doc/numpy/reference/generated/numpy.take.html

I don't know enough about sphinx to know how hard/easy this is, but it may be nice.

**Comment by jorisvandenbossche** [comment]
Yes, we can certainly do something like that. We only have quite some dynamically generated methods, so not sure how it works for those (but at least it can work for the others).

**Comment by jorisvandenbossche** [comment]
I was looking at some examples, and some give you not exactly what you want due to the implementation (eg `read_csv` pointing to `_make_parser_function` or `Series.add` to `_flex_method_SERIES`), but those are still a bit useful as in the end, it's how it is implemented. 

But I also noticed that functions with deprecations point to the decorators. For example `pandas.to_datetime` (http://pandas-docs.github.io/pandas-docs-travis/generated/pandas.to_datetime.html) points to https://github.com/pydata/pandas/blob/master/pandas/util/decorators.py#L65-L91. @chris-b1 Do you know if this would be fixable?

**Comment by jorisvandenbossche** [comment]
Ah, apparently this was fixed in python 3.5 (https://bugs.python.org/issue1764286), so yet another reason to update our doc building to python 3 :-)

**Comment by jorisvandenbossche** [comment]
EDIT: apparently only `inspect.getsource` was fixed, and not `inspect.getsourcefile`, pitty ..
