### ISSUE TITLE
DataFrame.asof

### ISSUE THREAD

**Issue by changhiskhan** [pydata/pandas#2941]
like Series.asof, should also take skipna={none, 'any', 'all'}

**Comment by bwillers** [comment]
I've been toying with this a little and it's not clear that it's possible to avoid doing the asof_locs call for each column, since they might have missings in different positions. So you probably dont end up gaining much over what the df.apply(lambda s: s.asof(t)) approach gives you.

However, if you don't want missings to be ffilled, then you only need to do it once. Perhaps it makes sense to have a flag argument which indicates whether the user wants missings to be ffilled during the asof operation?

**Comment by bwillers** [comment]
@shoyer  As discussed in #10266 this functionality is already available via `df.reindex(where, method='ffill')`, potentially with a dropna/fillna depending exactly what you want out at the end of the day. So we can probably close this this issue?

**Comment by shoyer** [comment]
Yep, let's close it.
