### ISSUE TITLE
PERF: Explore even faster path for df.to_csv

### ISSUE THREAD

**Issue by y-p** [pydata/pandas#3186]
iotop and a simple-mined c program indicates we're nowhere 
near IO-bound in df.to_csv, at about ~10-15x. 

It might be possible to speed things up considerably with a fast path
for special cases (numerical only) that don't need fancy quoting and other
bells and whistles provided by the underlying csv python module.

```c
#include <stdio.h>
#include <stdlib.h>

int main(int argc,char **argv)
{
    int i;
    FILE *f;
    char fmt[] = "%f,%f,%f,%f,%f\n";
    while (1) {
    f = fopen("out.csv","wb");
    for(i=0;i<1000000;i++) {
        fprintf(f,fmt, 1.0,2.0,3.0,4.0,5.0);
    }
    fclose(f);
    }
}
```

sustains about 30MB/s on my machine (without even batching writes)
vs ~2-3MB/s for the new (0.11.0) cython df.to_csv().

need to check if it's the stringifying, quoting logic, memory layout, or something 
else that constitutes the difference.

Should also yield insights for any future binary serialization format
implemented.

**Comment by wesm** [comment]
We will need to tackle this in the course of working on libpandas. I suggest we create a new set of issues around more optimally writing to CSV once we are ready to do that

**Comment by swt2c** [comment]
I know this is closed, but I would still like to work toward improving `to_csv` in Pandas 0.x.

I have been doing some profiling and so far I've found that the biggest (by far) CPU bottleneck in `write_csv_rows()` is this list assignment:

```
                row[1 + i] = data[i][j]
```
Per individual call, it doesn't take long, but since this gets executed for *every cell* it adds up.  It's not immediately obvious how to improve this, though, as Pandas seems to store its data in columns, whereas we need to get data out in rows.

**Comment by swt2c** [comment]
Also, `to_csv` is *much* slower when writing a sparse data frame.  In that case, the performance is dominated by `_to_native_types()`.
