### ISSUE TITLE
Test/fix case where use of "All" causes problems in pivot_table with margins=True

### ISSUE THREAD

**Issue by wesm** [pydata/pandas#3335]

**Comment by TheInan** [comment]
I'd like to take a stab at this if no one minds

**Comment by jreback** [comment]
go for it!

**Comment by TheInan** [comment]
Would it be an appropriate solution to have any instances of "All" used as an index or column changed to "All_" in the original dataframe and the resulting pivot table so that having a user use "All" as a column name will not cause issues anymore?

**Comment by shoyer** [comment]
I'm not sure exactly what "problems" are caused by this issue, but generally speaking it's a better idea to raise an exception and force users to take some fallback action themselves rather than silently proceeding with some guess about user intent.

**Comment by TheInan** [comment]
Alright then, I think I'll just scan the DataFrame for any instances of All being used as a value or column title, and if there is one, I'll raise an exception. The problem was that when margins was passed in as true, columns with the title "All" were added to the dataframe, and then add a later point, instances of "All" columns had aggregates data filled into them, so if the original data used "All" it was being replaced I think

**Comment by jreback** [comment]
need to define what is the incorrect behavior here first.

**Comment by TheInan** [comment]
So this is what I have so far showing the issue. What happens is that when aggregating the data, as the script is going through the columns, it looks for All columns to aggregate data under. When "foo" was changed to "All" in the next DataFrame, the output is clearly nothing like that of the first pivot table. As a result, its probably most appropriate to raise an error when "All" is being used as a data point since it would be more trouble than its worth to rewrite the code around just this corner case.

    import pandas as pd
    df = pd.DataFrame({'A' : ['one', 'one', 'two', 'three'] * 3,
    					'B' : ['A', 'B', 'C'] * 4,
    					'C' : ['foo', 'foo', 'foo', 'bar', 'bar', 'bar'] * 2,
    					'D' : [1,2,3,4,5,6,7,8,9,10,11,12],
    					'E' : [1,2,3,4,5,6,7,8,9,10,11,12]})
    df
<div style="max-height:1000px;max-width:1500px;overflow:auto;">
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>A</th>
      <th>B</th>
      <th>C</th>
      <th>D</th>
      <th>E</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0 </th>
      <td>   one</td>
      <td> A</td>
      <td> foo</td>
      <td>  1</td>
      <td>  1</td>
    </tr>
    <tr>
      <th>1 </th>
      <td>   one</td>
      <td> B</td>
      <td> foo</td>
      <td>  2</td>
      <td>  2</td>
    </tr>
    <tr>
      <th>2 </th>
      <td>   two</td>
      <td> C</td>
      <td> foo</td>
      <td>  3</td>
      <td>  3</td>
    </tr>
    <tr>
      <th>3 </th>
      <td> three</td>
      <td> A</td>
      <td> bar</td>
      <td>  4</td>
      <td>  4</td>
    </tr>
    <tr>
      <th>4 </th>
      <td>   one</td>
      <td> B</td>
      <td> bar</td>
      <td>  5</td>
      <td>  5</td>
    </tr>
    <tr>
      <th>5 </th>
      <td>   one</td>
      <td> C</td>
      <td> bar</td>
      <td>  6</td>
      <td>  6</td>
    </tr>
    <tr>
      <th>6 </th>
      <td>   two</td>
      <td> A</td>
      <td> foo</td>
      <td>  7</td>
      <td>  7</td>
    </tr>
    <tr>
      <th>7 </th>
      <td> three</td>
      <td> B</td>
      <td> foo</td>
      <td>  8</td>
      <td>  8</td>
    </tr>
    <tr>
      <th>8 </th>
      <td>   one</td>
      <td> C</td>
      <td> foo</td>
      <td>  9</td>
      <td>  9</td>
    </tr>
    <tr>
      <th>9 </th>
      <td>   one</td>
      <td> A</td>
      <td> bar</td>
      <td> 10</td>
      <td> 10</td>
    </tr>
    <tr>
      <th>10</th>
      <td>   two</td>
      <td> B</td>
      <td> bar</td>
      <td> 11</td>
      <td> 11</td>
    </tr>
    <tr>
      <th>11</th>
      <td> three</td>
      <td> C</td>
      <td> bar</td>
      <td> 12</td>
      <td> 12</td>
    </tr>
  </tbody>
</table>
</div>
    pd.pivot_table(df, values= 'D', index=['A','B'], columns=['C'], margins=True)
<div style="max-height:1000px;max-width:1500px;overflow:auto;">
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>C</th>
      <th>bar</th>
      <th>foo</th>
      <th>All</th>
    </tr>
    <tr>
      <th>A</th>
      <th>B</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="3" valign="top">one</th>
      <th>A</th>
      <td> 10</td>
      <td>  1</td>
      <td>  5.5</td>
    </tr>
    <tr>
      <th>B</th>
      <td>  5</td>
      <td>  2</td>
      <td>  3.5</td>
    </tr>
    <tr>
      <th>C</th>
      <td>  6</td>
      <td>  9</td>
      <td>  7.5</td>
    </tr>
    <tr>
      <th rowspan="3" valign="top">three</th>
      <th>A</th>
      <td>  4</td>
      <td>NaN</td>
      <td>  4.0</td>
    </tr>
    <tr>
      <th>B</th>
      <td>NaN</td>
      <td>  8</td>
      <td>  8.0</td>
    </tr>
    <tr>
      <th>C</th>
      <td> 12</td>
      <td>NaN</td>
      <td> 12.0</td>
    </tr>
    <tr>
      <th rowspan="3" valign="top">two</th>
      <th>A</th>
      <td>NaN</td>
      <td>  7</td>
      <td>  7.0</td>
    </tr>
    <tr>
      <th>B</th>
      <td> 11</td>
      <td>NaN</td>
      <td> 11.0</td>
    </tr>
    <tr>
      <th>C</th>
      <td>NaN</td>
      <td>  3</td>
      <td>  3.0</td>
    </tr>
    <tr>
      <th>All</th>
      <th></th>
      <td>  8</td>
      <td>  5</td>
      <td>  6.5</td>
    </tr>
  </tbody>
</table>
</div>




    df2 = pd.DataFrame({'A' : ['one', 'one', 'two', 'three'] * 3,
    					'B' : ['A', 'B', 'C'] * 4,
    					'C' : ['All', 'All', 'All', 'bar', 'bar', 'bar'] * 2,
    					'D' : [1,2,3,4,5,6,7,8,9,10,11,12],
    					'E' : [1,2,3,4,5,6,7,8,9,10,11,12]})


    df2




<div style="max-height:1000px;max-width:1500px;overflow:auto;">
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>A</th>
      <th>B</th>
      <th>C</th>
      <th>D</th>
      <th>E</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0 </th>
      <td>   one</td>
      <td> A</td>
      <td> All</td>
      <td>  1</td>
      <td>  1</td>
    </tr>
    <tr>
      <th>1 </th>
      <td>   one</td>
      <td> B</td>
      <td> All</td>
      <td>  2</td>
      <td>  2</td>
    </tr>
    <tr>
      <th>2 </th>
      <td>   two</td>
      <td> C</td>
      <td> All</td>
      <td>  3</td>
      <td>  3</td>
    </tr>
    <tr>
      <th>3 </th>
      <td> three</td>
      <td> A</td>
      <td> bar</td>
      <td>  4</td>
      <td>  4</td>
    </tr>
    <tr>
      <th>4 </th>
      <td>   one</td>
      <td> B</td>
      <td> bar</td>
      <td>  5</td>
      <td>  5</td>
    </tr>
    <tr>
      <th>5 </th>
      <td>   one</td>
      <td> C</td>
      <td> bar</td>
      <td>  6</td>
      <td>  6</td>
    </tr>
    <tr>
      <th>6 </th>
      <td>   two</td>
      <td> A</td>
      <td> All</td>
      <td>  7</td>
      <td>  7</td>
    </tr>
    <tr>
      <th>7 </th>
      <td> three</td>
      <td> B</td>
      <td> All</td>
      <td>  8</td>
      <td>  8</td>
    </tr>
    <tr>
      <th>8 </th>
      <td>   one</td>
      <td> C</td>
      <td> All</td>
      <td>  9</td>
      <td>  9</td>
    </tr>
    <tr>
      <th>9 </th>
      <td>   one</td>
      <td> A</td>
      <td> bar</td>
      <td> 10</td>
      <td> 10</td>
    </tr>
    <tr>
      <th>10</th>
      <td>   two</td>
      <td> B</td>
      <td> bar</td>
      <td> 11</td>
      <td> 11</td>
    </tr>
    <tr>
      <th>11</th>
      <td> three</td>
      <td> C</td>
      <td> bar</td>
      <td> 12</td>
      <td> 12</td>
    </tr>
  </tbody>
</table>
</div>
    pd.pivot_table(df2, values= 'D', index=['A','B'], columns=['C'], margins=True)
<div style="max-height:1000px;max-width:1500px;overflow:auto;">
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>C</th>
      <th>All</th>
      <th>bar</th>
    </tr>
    <tr>
      <th>A</th>
      <th>B</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="3" valign="top">one</th>
      <th>A</th>
      <td>  5.5</td>
      <td> 10</td>
    </tr>
    <tr>
      <th>B</th>
      <td>  3.5</td>
      <td>  5</td>
    </tr>
    <tr>
      <th>C</th>
      <td>  7.5</td>
      <td>  6</td>
    </tr>
    <tr>
      <th rowspan="3" valign="top">three</th>
      <th>A</th>
      <td>  4.0</td>
      <td>  4</td>
    </tr>
    <tr>
      <th>B</th>
      <td>  8.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>C</th>
      <td> 12.0</td>
      <td> 12</td>
    </tr>
    <tr>
      <th rowspan="3" valign="top">two</th>
      <th>A</th>
      <td>  7.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>B</th>
      <td> 11.0</td>
      <td> 11</td>
    </tr>
    <tr>
      <th>C</th>
      <td>  3.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>All</th>
      <th></th>
      <td>  6.0</td>
      <td>  8</td>
    </tr>
  </tbody>
</table>
</div>
