### ISSUE TITLE
Support for multidimensional dtypes

### ISSUE THREAD

**Issue by alexbw** [pydata/pandas#3443]
With 0.11 out, Pandas supports more dtypes than before, which is very useful to us science folks. However, some data is intrinsically multi-dimensional, high enough dimensional so that using labels on columns is impractical (for instance, images). 

I understand DataFrames or Panels are usually the recommended panacea for this problem. This works if the datatype doesn't have any annotation. For instance, for each frame of a video, I have electrophysiology traces, timestamps, and environmental variables measured. 

I have a working solution where I explicitly separate out the non-scalar data from the scalar data. I use Pandas exclusively for the scalar data, and then a dictionary of multi-D arrays for the array data. 

What is the work and overhead involved in supporting multi-D data types? I would love to keep my entire ecosystem in Pandas, as it's much faster and richer than just NumPy data wrangling.

See below for the code that I hope is possible to run, with fixes.

If you can point me to a place in the codebase where I can tinker, that would also be much appreciated.

```
import pandas as pd
mydtype=np.dtype('(3,3)f4')
pd.Series(np.zeros(3,), dtype=mydtype)
```
```
Exception: Data must be 1-dimensional
```

**Comment by shoyer** [comment]
@alexbw I agree, I think this issue can be considered resolved -- this is not going to happen easily in pandas itself, and is probably better left to third party packages -- pandas does not need more scope keep. That said, I might leave it open if only so that something turns out when people search open GitHub issues for "multidimensional".

Thanks also for sharing your approach. I know I'm repeating myself in this issue, but I'd like to note again for the record that each of your problems is something that [xray](https://github.com/xray/xray/) is designed to solve (though it also tries to do more). Its `Dataset` object acts like your `Bunch` (I recently added attribute-style access for variables) but it does have support for simultaneous indexing of all variables. It also supports direct output to multi-dimensional netCDF4 files with optional chunking/compression, similar to what you accomplished with h5py (netCDF4 is a subtype of HDF5 with particular metadata conventions).

**Comment by alexbw** [comment]
I will check out Xray. I'm current a fan of the thinness of the Bunch
approach, but a lack of a global index is annoying. I am enjoying also the
efficiency of hand-tuned HDF5 data structures, I can go way beyond what
pandas can do out of the box by paying close attention to how data is
written. I am excited to see if xray helps automate that process (it
definitely doesn't have to be as manual as I currently do it).

**Comment by jreback** [comment]
closing this, but can comment on specific uses [here](https://github.com/pydata/pandas-design/issues/24), for pandas 2.0 designs.
