### ISSUE TITLE
Unfinished test case in pandas/io/tests/test_parsers

### ISSUE THREAD

**Issue by jtratner** [pydata/pandas#4782]
Any ideas on what this was supposed to be? (from 50ae5268)

```python
    def test_multiple_skts_example(self):
        data = "year, month, a, b\n 2001, 01, 0.0, 10.\n 2001, 02, 1.1, 11."
        pass
```

Came in a commit with release notes that said:
```diff
diff --git a/RELEASE.rst b/RELEASE.rst
index a82e511..607be2e 100644
--- a/RELEASE.rst
+++ b/RELEASE.rst
@@ -41,6 +41,9 @@ pandas 0.8.0
   - Add ``match`` function to API (#502)
   - Add Cython-optimized first, last, min, max, prod functions to GroupBy (#994,
     #1043)
+  - Dates can be split across multiple columns (#1227, #1186)
+  - Add experimental support for converting pandas DataFrame to R data.frame
+    via rpy2 (#350, #1212)
 
 **Improvements to existing features**
 
@@ -53,6 +56,7 @@ pandas 0.8.0
   - Can pass arrays in addition to column names to DataFrame.set_index (#402)
   - Improve the speed of "square" reindexing of homogeneous DataFrame objects
     by significant margin (#836)
+  - Handle more dtypes when passed MaskedArrays in DataFrame constructor (#406)
```

**Comment by gfyoung** [comment]
Based on the doc, I think it might have been this:
~~~python
>>> read_csv(StringIO(data), parse_dates={'date': [0, 1]})
        date    a     b
0 2001-01-01  0.0  10.0
1 2001-02-01  1.1  11.0
~~~
However, we have many tests for that now in <a href="https://github.com/gfyoung/pandas/blob/3ed01a04067302c2449524bd05e159ea2c894696/pandas/io/tests/parser/parse_dates.py">parse_dates.py</a> test.  @wesm, do you remember what the point of this test was since you were the one who added it?

**Comment by gfyoung** [comment]
Based on the doc, I think it might have been this:
~~~python
>>> read_csv(StringIO(data), parse_dates={'date': [0, 1]})
        date    a     b
0 2001-01-01  0.0  10.0
1 2001-02-01  1.1  11.0
~~~
However, we have many tests for that now in <a href="https://github.com/gfyoung/pandas/blob/3ed01a04067302c2449524bd05e159ea2c894696/pandas/io/tests/parser/parse_dates.py">parse_dates.py</a> test.  @wesm, do you remember what the point of this test was since you were the one who added it?

If not, we can simply remove it and close this issue.

**Comment by wesm** [comment]
Do not recall. Feel free to remove
