### ISSUE TITLE
read_csv dtype argument not working when there is a footer

### ISSUE THREAD

**Issue by socheon** [pydata/pandas#5232]
xref #7141
 
Datafile test.csv
-----------------------

col1|col2
a|438087272980
b|399432587827
c|592706116147
d|1584843561523
footer 1

Command
--------------
print pd.read_csv('test.csv', sep='|', skipfooter=1, dtype={'col2':'object'}).dtypes

Output
---------
col1    object
col2     int64
dtype: object

Expected Output
------------------------
col1    object
col2    object
dtype: object

Platform
------------
Windows XP, Python 2.7, Pandas version 0.11.0

**Comment by Twizzledrizzle** [comment]
skip_footer in the c-parser would be nice!

**Comment by gfyoung** [comment]
`skip_footer` would indeed be nice to add to the C engine.  However, the implementation is not so straightforward.  In abstract, you need to count the number of lines and then figure out the line number cutoff, but that is assuming you have correctly-formatted data.  What happens if your data is not correctly-formatted?  How do you proceed with the counting?  In the Python engine, it's simple: the CSV reader will most likely complain and break, whereas the C engine supports different types of messages for error handling/warning.

**Comment by gfyoung** [comment]
@jreback : I think this issue can be closed but it has boiled down to either requesting `dtype` in the Python engine or `skipfooter` in the C engine, both of which are already part of the tracker in #12686.

**Comment by jreback** [comment]
closed as already marked in other issues specifically as @gfyoung indicates above
