### ISSUE TITLE
read_csv not correctly parsing dates when parse_dates is string and index_col not set

### ISSUE THREAD

**Issue by cancan101** [pydata/pandas#5636]
With:
```
csv="""A,B,C
1,2,2003-11-1
"""
```
These all work as expected:
```
In [40]: pd.read_csv(StringIO(csv), parse_dates="C",index_col="C").index[0]

Out[40]: Timestamp('2003-11-01 00:00:00', tz=None)

In [41]: pd.read_csv(StringIO(csv), parse_dates=["C"],index_col="C").index[0]

Out[41]: Timestamp('2003-11-01 00:00:00', tz=None)

In [42]: pd.read_csv(StringIO(csv), parse_dates=["C"]).C[0]

Out[42]: Timestamp('2003-11-01 00:00:00', tz=None)
```

but this does not parse the string:

```
In [39]: pd.read_csv(StringIO(csv), parse_dates="C",).C[0]

Out[39]: '2003-11-1'
```

**Comment by gfyoung** [comment]
@jreback : I think this issue can be closed.  The "buggy" example fails as expected because `parse_dates="C"` is the same as `parse_dates=True`, which will try to convert the `index` attribute of the resulting `DataFrame` as `datetime` objects per the `0.18.0` documentation.  By not specifying `index` to be the `C` column, it correctly does not parse it as a `datetime`.

**Comment by gfyoung** [comment]
@jreback : I think this issue can be closed.  The "buggy" example fails as expected because `parse_dates="C"` is the same as `parse_dates=True`, which will try to convert the `index` attribute of the resulting `DataFrame` as `datetime` objects per the `0.18.0` documentation.  By not specifying `index` to be the `C` column, it correctly does not parse it as a `datetime`.

**Comment by gfyoung** [comment]
@jreback : I think this issue can be closed.  The "buggy" example fails as expected because `parse_dates="C"` is the same as `parse_dates=True`, which will try to convert the `index` attribute of the resulting `DataFrame` as `datetime` objects per the `0.18.0` documentation.  By not specifying `index` to be the `C` column, it correctly does not parse it as a `datetime`.

**Comment by jreback** [comment]
```
parse_dates : boolean or list of ints or names or list of lists or dict, default False

    * boolean. If True -> try parsing the index.
    * list of ints or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3
      each as a separate date column.
    * list of lists. e.g.  If [[1, 3]] -> combine columns 1 and 3 and parse as
        a single date column.
    * dict, e.g. {'foo' : [1, 3]} -> parse columns 1, 3 as date and call result
      'foo'
```

So I think this should then have a nice meesage if a non-boolean scalar is passed as its not valid
