### ISSUE TITLE
Groupby within Groupby, or nested Groupby

### ISSUE THREAD

**Issue by ywhuofu** [pydata/pandas#7301]

**Comment by jreback** [comment]
closing - not enough info specified

**Comment by smcinerney** [comment]
I'm not the OP, but:
a) `df.groupby('a').groupby('b')` is a syntax error (docbug to show the right way?)
b) There are things wrong with nested groupby using `df.groupby(...).apply(top_grouper)`.
Even though they are separate functions, you can't avoid the result being a MultiIndex with the levels munged together, which you then have to manually extricate. Also,
b2) inside your custom function you need to use e.g.`head(1)` instead of `agg()` to prevent getting an unwanted default index 0,1,2... on the series and needing a slow call to `.reset_index()`. That unwanted default index then also gets munged into the unwanted MultiIndex.
