### ISSUE TITLE
IO: memory_map kw in read_csv

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#7477]
not sure of the purpose of ``memory_map`` (e.g. whether its needed anymore or not). might be an older option. If it IS current, then needs to be documented.

**Comment by gfyoung** [comment]
From what I can understand, `memory_map` differs in that files are mapped onto memory instead of being stored on disk.  The code traces back to `pandas/src/parser/io.c` which includes files like `sys/stat.h` and `sys/mman.h`, whose info can be found in the Linux man pages.  Thus, I don't even know if this actually applies to Windows for example.  It's hard to tell since there is a fall-back if the memory map fails.

Not sure how many people out there use this option (it's not tested too much), and I don't feel comfortable enough writing an explanation about it.  Probably someone with a better understanding of memory maps and those header files I mentioned could write something good.

**Comment by jreback** [comment]
closed by #13381
