### ISSUE TITLE
ENH: support both SQLAlchemy engines and connections

### ISSUE THREAD

**Issue by maxgrenderjones** [pydata/pandas#7877]
Feature request for supporting also Connection objects instead of only Engines.

Also reported in #8533, #10104 

---

My use case - I often add a week's worth of data (stored in a pandas dataframe) to an existing table. Before I add the data, I want to be able to delete any existing data for this week from the table, but I want the whole thing to be wrapped in a transaction so I'm not left in a mess halfway through.

Here's what I therefore want to be able to do

```python
# runs a transaction
with engine.begin() as connection:
    r1 = connection.execute(table.delete().where(table.c[WEEK]==week))
    data.to_sql(table.name, connection, if_exists='append')
```

i.e. my change is that I want to be able to pass a SQLAlchemy `Connection` object into `DataFrame.to_sql` instead of an `Engine`. (The underlying `Engine` of the `Connection` object can be accessed as `.engine`, so we should still be able to pull metadata etc)

**Comment by tr11** [comment]
@artemyk, what is the advantage of using a sqlalchemy engine instead of a connection? Going through the io/sql.py code, we really only use `has_tables` and `table_names` functions of the engine, which is not that much of an issue since we can recover the engine from the connection (using the engine attribute of the connection).  

In fact, it seems to make more sense for the scope of pandas to operate at the connection level only. That way the user can have full control over sqlalchemy connection issues such as isolation levels, nested transactions/savepoints, etc (see [sqlalchemy engines and connections](http://docs.sqlalchemy.org/en/latest/core/connections.html)).

Maybe we could default to use connections and create our own connection in case the user passes an engine? That way this would backwards compatible, but still allow for more advanced usage.

**Comment by artemyk** [comment]
@tr11 that sounds like a good idea to me.  @jorisvandenbossche thoughts?

**Comment by tr11** [comment]
OK, I really needed this right now, so I just hacked a quick version (https://github.com/tr11/pandas/commit/fe6fee394f78a908e74cf3675668a4475db3c616) that passes all the tests with engines or connections. I will add standard tests that use connection parameters and a couple other ones that show the new things that can be done with transaction rollbacks, using temporary tables, etc.  If there is any interest in merging this, I can also update the documentation before submitting a pull request.

**Comment by jorisvandenbossche** [comment]
@tr11 Sorry for the slow reaction here! 
Indeed, that looks like a good idea. If you would still want to make a PR for this (with tests and examples/docs), or give some comments on the newly opened PR #10105, that would be really great

**Comment by graingert** [comment]
I've updated the PR with these changes, and added tests
