### ISSUE TITLE
BUG: DataFrame outer merge changes key columns from int64 to float64

### ISSUE THREAD

**Issue by miketkelly** [pydata/pandas#8596]
```
import pandas as pd

df1 = pd.DataFrame({'key': [1,2,3,4], 'val1': [1,2,3,4]})
df2 = pd.DataFrame({'key': [1,2,3,5], 'val2': [1,2,3,4]})

df = df1.merge(df2, how='outer')
```

Was expecting `key` to stay int64, since a merge can't introduce missing key values if none were present in the inputs.

```
print df.dtypes

key     float64
val1    float64
val2    float64
dtype: object
```

Version 0.15.0-6-g403f38d

**Comment by bstempi** [comment]
Bump.  I'm experiencing this when doing outer joins as well.

Does anyone have a work-around for the time being?  E.g., an easy way to either convert the data types back or to prevent it from happening in the first place?  I don't want to end up in a position where going from `int64`-> `float64` causes any issues.

**Comment by jreback** [comment]
no easy way around this. you can simply convert the dtypes for the keys after.

**Comment by timseries** [comment]
Presently having an issue with this. The loss of precision from int64->float64 is problematic for me as I'm working with data that is stored as an int64 type. 

I'm not sure if converting the dtypes after the merge operation will work if precision is lost..., if I'm understanding @jreback 's solution correctly.

**Comment by abbradar** [comment]
Should this be fixed in 0.19.2? I see this:

```
info = pd.read_csv(filename + '.info', sep=' ', index_col=0, names=('req_id', 'user_req_id', 'recv_ticks'), dtype={'req_id': np.uint32, 'user_req_id': np.uint32, 'recv_ticks': np.uint32}, header=None)
send = pd.read_csv(filename + '.send', sep=' ', index_col=0, names=('req_id', 'send_ts'), dtype={'req_id': np.uint32, 'send_ticks': 'datetime64[ns]'}, header=None)
transmit = pd.read_csv(filename + '.transmit', sep=' ', index_col=0, names=('req_id', 'ts_ticks'), dtype={'req_id': np.uint32, 'ts_ticks': np.uint32}, header=None)

data = info.join(send).join(transmit)

print(transmit['ts_ticks'].dtype, data['ts_ticks'].dtype)
# uint32 float64
```

**Comment by MagdalenaDeschner** [comment]
I have the following issue: dtype of a column other than the key changes from int to float after left joining with pd.merge(). Please tell me, if you need more information to dig into!
merge2 = pd.DataFrame(pd.merge(merge1, appevents, how="left", on="event_id"))

**Comment by suvayu** [comment]
I have the same issue as @MagdalenaDeschner,  `dtype` of other columns change to float.  This is troublesome because in my case some of those columns store ids and counts.  You can see the issue by varying the example in the [changelog](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#merging-changes) a bit.

    >>> df1 = pd.DataFrame({'key': [1, 2], 'v1': [20, 30]})                                                                    
    >>> df2 = pd.DataFrame({'key': [2, 2], 'id': [1, 2], 'v2': [21, 31]})
    >>> df1
       key  v1
    0    1  20
    1    2  30
    >>> df2
       id  key  v2
    0   1    2  21
    1   2    2  31
    >>> pd.merge(df1, df2, how='outer')                                          
       key  v1   id    v2
    0    1  20  NaN   NaN
    1    2  30  1.0  21.0
    2    2  30  2.0  31.0

Interestingly `inner` does not have the issue, also it seems to be happening for columns in one of the dataframes (maybe the repeated value of  the key in the second dataframe is why).

    >>> pd.merge(df1, df2, how='inner')
       key  v1  id  v2
    0    2  30   1  21
    1    2  30   2  31

**Comment by jreback** [comment]
@suvayu that is the expected outcome for outer, you are introducing NaN's force the conversion

**Comment by suvayu** [comment]
Hmm, I guess that makes sense.  Sorry for the noise.

**Comment by theholy7** [comment]
I definitely lose data on the int->float conversion during the merge. When i cast back from float->int my id's stop working.

Any idea how this can be avoided if at all?

**Comment by immerrr** [comment]
@theholy7 old-school numpy integers don't have NaN values, so the only option is to use a different dtype. Depending on the performance drop you can bear your options are:
- `dtype='object'` -- probably worst possible case, all values are stored as garbage collected PyObjects (consuming 28 bytes instead of 8) and no vectorization is possible
- `dtype='category'` -- all values are stored as integer indexes into a different numpy array, much cheaper memory wise, but arithmetic operations might be tricky 
- `dtype='Int64'` -- [new kid on the block](https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html#integer-na), should be most efficient on both memory and arithmetics, but still marked as experimental API

**Comment by kuraga** [comment]
Are there new thoughts/issues/PRs for 3.0.5 time?

```python
>>> import pandas as pd

>>> a = pd.DataFrame({ 'c1': [0, 1], 'c2': [3, 4]})
>>> a.dtypes
c1    int64
c2    int64
dtype: object

>>> b = pd.DataFrame({ 'c1': [1, 2], 'c2': [3, 4]})
>>> b.dtypes
c1    int64
c2    int64
dtype: object

>>> c = pd.merge(a, b, how='outer', on='c1')
>>> c.dtypes
c1        int64
c2_x    float64
c2_y    float64
dtype: object
```

**Comment by kuraga** [comment]
Pointed as successors:

- #32265,
- #58243,
- #58988.
