### ISSUE TITLE
Improve clarity around when SettingWithCopyWarning can be ignored (if ever?)

### ISSUE THREAD

**Issue by maxgrenderjones** [pydata/pandas#8730]
I [Edit: thought I got] a `SettingWarningCopyWarning ` when running the following code:
```python
frame[columnone][frame[columntwo]>x]=y
```
The docs seem to imply that I can safely ignore this error.
```python
# passed via reference (will stay)
In [273]: dfb['c'][dfb.a.str.startswith('o')] = 42
```
Is it therefore generally true that I can always ignore errors when the command I'm running is of the form:
```python
frame[columnames][booleanconditiononframe]=x
```

I use this all the time, and I *think* it always works. If that's true, it would be great if it was specifically called out in a 'you can ignore this warning when...' section. If that's not true (e.g. it works for scalar x / numeric x but not for series x), it would be great if that were called out too.

Sorry if this seems trivial, but I'm trying to explain this to a colleague who's new to pandas and he's confused, and it looks like even old hands can be confused when confronted with this warning (see #6757).

[Edit: looking at his code again, I suspect the SettingWithCopy warning was from a different line of code - (I wish warnings made it clear where they were from). All the same, it would still be great if the docs could be clear if there are circumstances where you always get a reference rather than a copy]

**Comment by adamklein** [comment]
One of my users has code similar to this:

    df1 = DataFrame({'x': Series(['a','b','c']), 'y': Series(['d','e','f'])})
    df2 = df1[['x']]
    df2['y'] = ['g', 'h', 'i']

And gets the warning. However, in the code base, lines 2 and 3 are quite far removed. So it's almost impossible to realize the warning stems from line 2, (because the warning happens on execution of line 3, far away). I don't know if anything can be done about this, but it can be a head scratcher to track down the source of the warnings.

**Comment by jreback** [comment]
@adamklein 

The reason the above triggers the warning is the soln that is for this case below is triggered. Basically you reindex a frame to another frame, which 'remembers' that this happend (via the ``.is_copy`` attribute). Then if a chained indexing operation happens the warning can be triggered.

```
In [3]: df = pd.DataFrame({'a': list(range(4)), 'b': list('ab..'), 'c': ['a', 'b', np.nan, 'd']})

In [4]: mask = pd.isnull(df.c)

In [5]: df[['c']][mask] = df[['b']][mask]
/Users/jreback/anaconda/bin/ipython:1: SettingWithCopyWarning: 
```

What you are doing in your example and what I am showing are different, e.g. you are adding a column, while the above is a masked indexing on the rows. But the only way to detect this is to set ``.is_copy`` in the first place, otherwise the logic becomes crazy complex.

Now I can turn off this case, so what you are doing will not trigger the warning, but my example above will no longer warn.

I suspect that what you are doing is much more common, so this would eliminate this false positive while NOT warning when it *should* in a type of chained indexing. 

As you can guess detecting chained indexing is actually quite complex.

**Comment by jreback** [comment]
ok, see #9659 this should fix @adamklein issue.

**Comment by kay1793** [comment]
> The reason the above triggers the warning is the soln that is for this case below is triggered. 

wow I bet *that* triumph of grammer crashes [NLTK](http://www.nltk.org/).

**Comment by adamklein** [comment]
:)
