### ISSUE TITLE
ME breakpoints in fama french factors library

### ISSUE THREAD

**Issue by MichaelWS** [pydata/pandas#8842]
ME_breakpoints.zip is not read because it is a different format.
In this zip, there is only one file "ME_Breakpoints.txt".  How should this be handed?

**Comment by gitmmeanwell** [comment]
Not sure this is right place for this but new to Pandas and trying FamaFrench pandas:
This works:
# read data from Ken French's website 
ff = web.DataReader('F-F_Research_Data_Factors', 'famafrench')[0] 
# NB:  ff.xs is a conflict, rename to xsm  
ff.columns = ['xsm', 'smb', 'hml', 'rf']

But this does not
# read data from Ken French's website 
ff = web.DataReader('F-F_Momentum_Factor', 'famafrench')[0] 
ff.columns = ['mom']
Throws KeyError: 0
Any suggestions?  Thanks

**Comment by jorisvandenbossche** [comment]
@gitmmeanwell `web.DataReader('F-F_Momentum_Factor', 'famafrench')` returns a dict with keys `[1, 2]`, so that is why get a KeyError.

**Comment by gitmmeanwell** [comment]
Thanks for the reply - any suggestions on how to resolve?  New to pandas
and data frames.

**Comment by jorisvandenbossche** [comment]
Not using 0 in `web.DataReader('F-F_Momentum_Factor', 'famafrench')[0]`?

I don't know what you are trying to achieve, so difficult to say. I also don't exactly know the structure of that dataset. So you will have to specify your question more (but maybe http://stackoverflow.com/ is a better place to ask)

**Comment by gitmmeanwell** [comment]
Here is some more info on Use case - I'll head to StackOverflow to research
further unless you have any final comments?  Thanks again!

Goal: use Pandas to read file from FamaFrench website and perform some
analysis.

# load packages (if it's redundant it'll be ignored)
import pandas.io.data as web
# anything after the hashtag is a comment
#%reset
import datetime as dt
import matplotlib.pyplot as plt    # plotting tools

# the next one is an IPython command: it says put plots here in the
notebook, rather than in a separate window.
%matplotlib inline
# read data from Ken French's website
ff = web.DataReader('F-F_Momentum_Factor', 'famafrench')
# NB:  ff.xs is a conflict, rename to xsm
ff.columns = ['mom']


txt file structure example (file downloaded to local c:\) - this is the
file F-F_Momentum_Factor that is read from site and loaded to local c:\

This file was created by CMPT_ME_PRIOR_RETS using the 201412 CRSP
database.  It
contains a momentum factor, constructed from six value-weight portfolios
formed
using independent sorts on size and prior return of NYSE, AMEX, and NASDAQ
stocks.
Mom    is the average of the returns on two (big and small) high prior
return portfolios
minus the average of the returns on two low prior return portfolios.  The
portfolios
are constructed monthly.  Big means a firm is above the median market cap
on the NYSE
at the end of the previous month; small firms are below the median NYSE
market cap.
Prior return is measured from month -12 to - 2.  Firms in the low prior
return
portfolio are below the 30th NYSE percentile.  Those in the high portfolio
are above
the 70th NYSE percentile.

Missing data are indicated by -99.99 or -999.

          Mom
192701   0.44
etc
etc

**Comment by gitmmeanwell** [comment]
Moving comment/issue to StackOverflow.

**Comment by MichaelWS** [comment]
web.DataReader('F-F_Momentum_Factor', 'famafrench') creates a dict with keys 1,2. 1 works for daily returns.  
when we break this into a separate project, I would eventually like to make the keys ,"daily", "monthly", "annual" so it's easier to understand.

**Comment by jorisvandenbossche** [comment]
@MichaelWS be sure to open an issue for that at https://github.com/pydata/pandas-datareader/issues to not forget that! (as the separate project is already there)

**Comment by jorisvandenbossche** [comment]
and maybe also move this issue if you want

**Comment by jorisvandenbossche** [comment]
Closing this in favor of https://github.com/pydata/pandas-datareader/issues/21
