### ISSUE TITLE
ENH: add missing methods to .dt for Period

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#8848]
methods
- to_timestamp
- asfreq

properties
- start_time/end_time

**Comment by rosnfeld** [comment]
@jreback I just want to make sure I understand this issue. If there's a series of Period objects, there are some additional methods desired on the .dt accessor? And these would be the same for PeriodIndex, as from looking at the code it seems that PeriodIndex is what's really behind the scenes of the .dt accessor?

I should note there's a whole host of methods that are available to datetime_series.dt that aren't on period_series.dt, including: ceil/floor/round, is_{month,quarter,year}_{start,end}, microsecond, nanosecond, normalize, tz, tz_convert, tz_localize.

**Comment by rosnfeld** [comment]
Now that I've played with this code a bit, not sure a lot of those methods make sense for PeriodIndex/period_series.dt. I think a new issue can be raised if some of them should be implemented. (a harder task than what this issue was, which was mostly just exposing on .dt what was already done on PeriodIndex)
