### ISSUE TITLE
DISCUSS: move online data reader subpackages to separate project?

### ISSUE THREAD

**Issue by jorisvandenbossche** [pydata/pandas#8961]
Opening an issue to discuss this: **should we think about moving the functionality to read online data sources to a separate package?**

This was mentioned recently here https://github.com/pydata/pandas/issues/8842#issuecomment-63456052 and https://github.com/pydata/pandas/pull/8631#issuecomment-61805926

Some reasons why we would want to move it:
- This often needs much more urgent releases than pandas to fix changes in the remote sources. So with separate release cycle, this can speed up propagation of bugfixes to users
- More general: to limit the scope of pandas as the core project, and to encourage that some people take ownership of this subproject (which is easier as a separate project?), publicize it separately, ..

Some questions that come to mind:

- What should we move? (everything in [remote_data.rst](http://pandas.pydata.org/pandas-docs/stable/remote_data.html)?)
  -  Everything in ``io.data``? (the `DataReader` function for Yahoo and Google Finance, FRED and Fama/French, and the `Options` class
  -  Also `io.wb` (certain World Bank data) and `io.ga` (google analytics interface)?
- Should we move it all to one separate project, or to multiple?
- Are there outside of pandas already some packages like this? (possibilities to merge with that/collaborate/..)
- Who would be interested to take this up? To be a maintainer of such a package?

Pinging some of the people have worked on these subpackages (certainly add others if you know): 
@dstephens99 @MichaelWS @kdiether @cpcloud @vincentarelbundock @jnmclarty 
@jreback @immerrr @TomAugspurger @hayd @jtratner

**Comment by bashtage** [comment]
I don't think `stata` should be considered unstable. It is heavily tested, written against the Stata file format spec, and hasn't had a show stopper bug* in a number of releases (mostly small things like increasing file size in a read/write cycle).

*Excluding big endian issues, which are probably not important for users of big endian systems, assuming these exist.

**Comment by femtotrader** [comment]
For doc Read the docs is very convenient https://readthedocs.org/

**Comment by jreback** [comment]
@femtotrader and for a ``datareader`` package this will probably work. Readthedocs won't handle a full build which requires things like compiling (that's the reason pandas does not host this way).

**Comment by hayd** [comment]
@jreback how would readthedocs for a datareader package sit in the pandas docs (url-wise)? Tbh could just keep the docs as they are on the pandas side, mostly updates to datareaders are just fixes to external APIs?

From the (pretty trivial) exercise I did splitting out datareaders, I think we should split it - it means people can use "old" pandas and up-to-date (working) datareaders. I think should do the same for `pandas_compat`. Happy to put a PR together and see if it just works<sup>TM</sup>.

Not sure how fits with @femtotrader's thoughts?

**Comment by femtotrader** [comment]
You really want my opinion ;-)

My `DataReader` version is better because it supports cache and "that's useful for me"<sup>TM</sup>  ;-) (but also some other people)

but yes I think that we should split datareaders to a separate GitHub project, a separate pip package, a separate testing and continuous integration process and have an easy doc build using readthedocs
so update will be easier

Maybe we should do this in 2 steps.

First move and keep exactly same code.
Then add my wonderful cache features in a second step ;-)
@twiecki seems interested for zipline see https://github.com/quantopian/zipline/pull/398#issuecomment-69718174

That's just my opinion.

**Comment by jreback** [comment]
ok, let's create another package under pydata.

- name: ``pandas-datareader``, ``datareader`` ? (it will be under ``pydata/.....`` but the actual package name will user visible
- I will add the pandas devs and other interested parties as commiters
- would suggest that 0.1 be exactly the same as the pandas tests/docs/API
- would suggest that any api transitions be backward-compat for a while
- this should be a released package before any changes to pandas
- mark any issues here and open corresponding ones in datareader

**Comment by femtotrader** [comment]
I also forget to say that I can also grant access to https://pypi.python.org/pypi/pandas_datareaders (even ownership to @wesm and @jreback because they are pandas pypi package owner). I just want this part of Pandas to be improved.

Please just say me what to do now. I will be able to help friday and a part of next week.

Maybe we could first move the doc.

**Comment by hayd** [comment]
@femtotrader what's the backwards compat situation with using pandas_datareaders vs pandas.

That is: What we want IMO is to just drop in pandas_datareaders (or whatever) into pandas.io, that way we don't break users code (whilst it's independent/for now they must replace from `pandas.io import ...` with `from pandas_datareader import ...` and it "just work"). If we do that does your lib pass the tests?

Make sense?

(also, does your lib work on 3.X? you should add that to travis.)

IMO docs can be last, since if we were to change this it could remain completely behind the scenes. I guess I don't know how much API you've changed/improved and so what a good migration strategy is.

**Comment by wesm** [comment]
FWIW, I have often thought about the fact that pandas is turning into a monolithic "kitchen-sink" package, and it might make sense to component-ize a bit (data readers/writers is an obvious one) so that folks can get new data sources without having to deal with upgrading their code bases to account for little API changes (typically where they were accidentally relying on some undocumented, unspecified, or untested) behavior that breaks their code. Now, that's happening less and less now. And nothing to stop you from having all the `DataFrame.to_*` methods, though perhaps that's starting to get a bit busy =)

**Comment by femtotrader** [comment]
@hayd my lib won't pass the test because in my lib `DataReader` is an object with a `get` method
I've never test with Python 3.
see for example https://github.com/femtotrader/pandas_datareaders/blob/master/tests/test_datareader_google_finance_daily.py
So we should forget my lib for now.
My idea was to have a DataReader object which could have a `expire_after` parameter defined at init.

An other example of my DataReader object is here
https://github.com/femtotrader/pandas_datareaders/blob/master/pandas_datareaders/datareaders/openexchangerates.py
https://github.com/femtotrader/pandas_datareaders/blob/master/tests/test_datareader_openexchangerates.py
there is a `get` method to get exchange rate matrix
but also a `convert` method to convert currencies

Maybe that wasn't a good idea...
maybe we should still keep `DataReader` a function (and have all the current code not modified).
We should just move current pandas code and doc first.

In a second step, we will be able to add cache mechanism anyway passing `session` parameter to `DataReader` function (this parameters being defined as `None` by default) so it should be backward-compat.

    import requests_cache
    session = requests_cache.CachedSession(cache_name='cache', backend='sqlite', expire_after=60*60)
    df = web.DataReader(symbol, 'google', start, end, session)

What is your opinion about it ?

**Comment by hayd** [comment]
Ok, let's do this, theres a been 2 patches since I migrated it a month ago, so will do the following.

- Apply those patches to hayd/...
- Push to pydata/... (Can I just do that @jreback, we need a name eitherway...)
- Push package to pypi (Note: failing on 0.10- IIRC due to compat)
- Replace on pandas and make PR to see if it still passes all the tests
- Make similar lib for compat
- Get datareaders working on older pandas...

Then @femtotrader add in what you've learned making pandas_datareaders (hopefully with minimal/no breaking API changes). Caching + sessions sounds great!

I'm not sure we can use `pandas_datareaders` as the pypi name as that conflicts with your package (and will break code for people... including yours!) What about just `pandas_data` or `pd_datareaders`?

**Comment by femtotrader** [comment]
You can take the project on Pypi it doesn't matter for me

we just need to use a version number > 0.0.2 for the official pandas datareader.

My (very few) users will have to use version 0.0.2 of my DataReader or wait for 0.2 pandas official datareader (because there will be no cache in 0.1)

**Comment by femtotrader** [comment]
I've just add @wesm and @jreback as owner

**Comment by jorisvandenbossche** [comment]
On a name, I more like "pandas-datareader" instead of "pandas_datareader", and then eg just `datareader` to import. But, of course, just a matter of taste ..

**Comment by jorisvandenbossche** [comment]
@hayd What do you mean with "make similar lib for compat"?

And with "Replace on pandas"? -> I think we jsut leave it as it is for now, and if everyting is in place just put a deprecation warning on it? (and then remove in a more future release)

On "Get datareaders working on older pandas...", I think up to 0.11 (it is now?) is already very nice (if it would be much effort)

**Comment by hayd** [comment]
@jorisvandenbossche sorry current failure is 0.12- (see https://travis-ci.org/hayd/pandas_data_readers/builds/43218562) it's basically just pandas.compat not having certain functions back then - if we make pandas-compat a sep package we wouldn't have that issue (and I think it would work on 0.10+ for free).

I don't see the reason to not just include it, what's the value in deprecate/remove?

**Comment by jreback** [comment]
I agree with joris here

I will setup pandas-datareader later in pydata 

then I would suggest that the first version just be the exact version that pandas has

if someone wants to modify it later on 
no problem

a PR to replace the current pandas calls with the new pandas-datareader can be done in 0.16 after the new repo is up tested and released on pypi / conda

**Comment by hayd** [comment]
@jreback the snapshot I did back in December is exactly that, the work is done (modulo a name change)... so I think we're all in agreement here.

*As mentioned there's been two "datareader" commits since then: https://github.com/pydata/pandas/commit/f88f15b60d4b50391b8a188cf05bbc4643d4f494 and https://github.com/pydata/pandas/commit/b65839d8081ac6830cc09f44f697178817a356d3.*

**Comment by jreback** [comment]
I created this new repo: https://github.com/pydata/pandas-datareader
and invited everyone on this issue (and all of the pandas-dev members). You should all now have push/pull access. I'll patch in the travis hook.

**Comment by jnmclarty** [comment]
> because it supports cache
@femtotrader Uncanny timing.

**Comment by hayd** [comment]
I'm going to force push my repo to master, hope no-one complains too much... can correct (whatever is the correct thing to do) if it's an issue.

@jreback Could you look over the setup.py, change the author etc and push to pypi ?

I've fixed the tests and updated with recent commits *except*  https://github.com/pydata/pandas/commit/f88f15b60d4b50391b8a188cf05bbc4643d4f494 as it's a (small) API change so wasn't clear what to do there. Should probably just apply it.

**Comment by femtotrader** [comment]
I renamed my package `pandas_datareaders_unofficial`.
I will delete it on Pypi (my very few users will have to install from source)
but I get an Amiga error (Error 503 backend read error - Guru Mediation)

**Comment by hayd** [comment]
Needs some readme + docs/ readthedocs love...

I totally missed `ga.py` and `gbq.py`, should these be included, should anything else?

**Comment by jorisvandenbossche** [comment]
I can look at the docs if you want.

But some other things to discuss:

- *How do we see it's future in pandas?*:
  - @hayd I have the impression you are suggesting that we still include the datareaders in pandas (a certain version), but that users if they want a latest update, can install the separate package? Is that correct?  
    And how would that be done? (with adding it as a git submodule?)
  - I had originally more the idea that we would deprecate the functions in pandas and point users to the new package, so that after some transition period, everybody uses the separate package, and the code can be removed from pandas. 
- *What do we do with the other mentioned packages?* (at least `ga.py` and `gbq.py` are mentioned above)?
  - I personally would beware that we don't make the scope of `pandas-datareader` too broad. We split this off because pandas is becoming to big, so let's keep the new package focused (so we actually should try to define what this focus should be). That said, I can't really judge on `ga.py`, but I would say that `gbq.py` does not really belong in the new package, as this is really a storage platform to write to / read from?
- Maybe we should put something on the mailing list about this?

**Comment by hayd** [comment]
@jorisvandenbossche No I was just thinking it as a dependancy, e.g. have `pandas.io.data = pandas_datareader.data`, these can/would be updated by the user. That way no need to deprecate/break code (but still we remove the code from pandas).

These are ~~packages~~ parts of pandas which periodically break due to external API changes, I kind of think they (data wb ga gbq) belong together (though share the concern about making it to big, maybe they can be separate - I don't think it matters too much, they're pretty stable atm).

*Similarly I think extracting out pandas.compat could be useful for other packages (which depend on pandas).*

**Comment by femtotrader** [comment]
In my mind `ga.py` and `gbq.py` should also be part of `pandas-datareader`.

I also think that `pandas.io.data = pandas_datareader.data` and having datareader a dependency is a good idea so it won't break any code for now (but I'm not a specialist)

**Comment by jreback** [comment]
all of the modules moved to ``pandas_datareader`` are pulling from named web-sources. I could buy ``ga.py``, as this is similar, though it pulls from 'private' sources.

``gbq.py`` OTOH is much more like ``sql/hdf/excel`` where it provides a 2-way connection to this data. Yes it is web-based but that is incidental.

**Comment by jorisvandenbossche** [comment]
agree with @jreback on `gbq.py`, which is what I tried to say above. There is a clear difference between reading in existing remote data sources and write/read to/from a storage place (although it is remote).

About having `pandas.io.data = pandas_datareader.data` and then having `pandas_datareader` as a dependency. I am not fully convinced on this, some concerns:

- I don't know if we want more dependencies (although it is optional, still, we already have a huge list of those)
- Isn't it more clear to users to just have it as an explicit separate package? As they will also have to update it separately, etc. Eg you then get people updating their pandas and questioning why the datareader was not updated.
- What is the advantage of having it like this? In that they don't have to change their import statements. But once changing the import statement from `from pandas.io import data` to `from pandas_datareader import data` does not seem like that much of problem if we document/communicate that clearly.

**Comment by jreback** [comment]
see issue here: https://github.com/pydata/pandas-datareader/issues/15

in a nutshell. I think its important that the first release (say 0.1) of ``pandas-datareader`` and 0.16.0 be basically identical. Then ``pandas-datareader`` can update at its own pace.

**Comment by hayd** [comment]
@jreback any reason for pandas not to do the import for you going forward?

    pandas.io.web = data_reader.web

Either as a dependency or as a soft dependency (e.g. throw an error that you need to `pip install pandas-datareader` to use pandas.io.web) ? (One aim of pandas-datareader is to be backwards compatible, and work on older version of pandas. )

**Comment by jreback** [comment]
I think a soft dep is fine 
but iirc the idea was to basically leave the code completely as is till say 0.17 then change it?

**Comment by hayd** [comment]
@jreback sounds good!

**Comment by jorisvandenbossche** [comment]
Another question: what about the docs? (I started with that https://github.com/pydata/pandas-datareader/pull/18, but was not fully sure about the path to follow)

Should they also stay in the pandas docs? Or refer to the pandas-datareader docs? Wich import do we use there? The 'real' `pandas_datareader` or `pandas.io.data` one? 
I still find that keep on using `pandas.io.data` as the import path in the long run (also when the code is removed from the pandas codebase itself) will only cause confusion.

**Comment by jreback** [comment]
closed by #10870
