### ISSUE TITLE
Shift Inplace in DF

### ISSUE THREAD

**Issue by sirinath** [pydata/pandas#9207]
Is it possible to add in place shifting

**Comment by shoyer** [comment]
We generally prefer not to implement in-place operations unless there are clear performance benefits because they can lead to confusing behavior, especially with chained operations. For example `df['column'].do_something_inplace()` modifies the series `df['column']` --- and not, necessarily, the original dataframe `df`.

**Comment by jreback** [comment]
@sirinath most in-place operations are in fact NOT inplace. This was put 'inplace' a while ago (pun intended!). as @shoyer says, not really in favor of these.

**Comment by shoyer** [comment]
To be clear, the recommend way to do an "in-place" shift would be to write `df = df.shift()`

**Comment by 121onto** [comment]
It seems like the inplace option provides added flexibility.  For example, it allows to me modify a DataFrame by calling a function, without needing to return a copy:

```
def my_function(frame):
    frame.some_operation(inplace=True)
```

**Comment by jreback** [comment]
@121onto inplace setting violates the purity of functions. you can certainly use it if you want. And I suppose we would accept a PR to implement. But beware, in general there is no actual benefit to doing things inplace.

**Comment by kakl** [comment]
Hello.
How can I write this without inplace?

xx['max'] = xx.iloc[:,250:260].idxmax(axis=1)
xx.iloc[:,269:513].loc[xx['max']==278].shift(1,axis=1, inplace=True)
