### ISSUE TITLE
Complete rewrite of bottleneck package

### ISSUE THREAD

**Issue by kwgoodman** [pydata/pandas#9421]
I have completely rewritten the bottleneck package. Since it is an optional dependency of pandas I thought you might want to test it before I release.

Release notes are here: https://github.com/kwgoodman/bottleneck/blob/master/RELEASE.rst
Branch: master 

Please report results here: https://github.com/kwgoodman/bottleneck/issues/96

**Comment by shoyer** [comment]
The only breaking change I noticed for pandas is that the new version of bottleneck changes the behavior of `nansum` for all NaN arrays to return 0, rather than NaN. Otherwise the test suite ran successfully (see the linked bottleneck issue).

This shouldn't be a blocker for the bottleneck release but we should address this nansum change for pandas 0.16 (see #9422).

**Comment by jreback** [comment]
1.0 pretty popular now. so all except for the nansum change #9422 this issue not relevant anymore.
