### ISSUE TITLE
.apply converting string to date

### ISSUE THREAD

**Issue by ashishsingal1** [pydata/pandas#9477]
The .apply on DataFrame is converting my string to a date. I have posted this on StackOverflow:

http://stackoverflow.com/questions/28487105/pandas-on-apply-passing-wrong-value

I'm not sure if I'm doing something wrong or it is a bug, but it seems quite strange behavior. 

Example [here](http://stackoverflow.com/questions/28550339/interesting-pandas-loc-behavior?noredirect=1#comment45415876_28550339)

```
In [8]: df = pd.DataFrame({'wing1':wing1, 'wing2':wing2, 'mat':mat}, index=belly)

In [9]: df
Out[9]: 
            mat wing1 wing2
216  2016-01-22  2T15   416
3T19 2019-09-07  4H19  4T20

In [17]: df.loc['3T19']
Out[17]: 
mat     2019-09-07 00:00:00
wing1   2015-02-16 04:19:00
wing2   2015-04-20 00:00:00
Name: 3T19, dtype: datetime64[ns]

In [18]: df.loc['216']
Out[18]: 
mat      2016-01-22 00:00:00
wing1                   2T15
wing2                    416
Name: 216, dtype: object
```

**Comment by jreback** [comment]
The converter is a little too agressive here as it should not try to convert this when the dtype is specified (as 'NOV' as a string is a valid datetime) and since there is another datetime it will try to coerce.
This should be passing ``False`` rather than ``True`` to the ``_try_cast`` [here](https://github.com/pydata/pandas/blob/master/pandas/core/series.py#L2635)

```
In [2]: Series([Timestamp('20130101'),'NOV'],dtype=object)
Out[2]: 
0   2013-01-01
1   2015-11-12
dtype: datetime64[ns]
```

not sure what else might break though

**Comment by jreback** [comment]
@ashishsingal1 pull-requests are welcome to fix this
