### ISSUE TITLE
Assignment from/to MultiIndexed columns should probably be symmetric

### ISSUE THREAD

**Issue by brianthelion** [pydata/pandas#9656]
This was counter-intuitive for me.
```python
    N = 5
    columns = pd.MultiIndex.from_tuples([('a', 0), ('a', 1), ('b', 0), ('b', 1)])
    df1 = pd.DataFrame(np.random.rand(N, 4), columns=columns)
    df2 = pd.DataFrame(np.random.rand(N), columns=['c'])
    df1_copy = df1.copy()
    df2_copy = df2.copy()
    df1_copy[df2.columns] = df2
    df2_copy[df1.columns] = df1
    print "===== A ====="
    print df1_copy
    print
    print "===== B ====="
    print df2_copy
```
gives
```
===== A =====
          a                   b                   c
          0         1         0         1          
0  0.540405  0.814476  0.923961  0.935421  0.909791
1  0.679014  0.220417  0.511039  0.117898  0.282063
2  0.428563  0.915760  0.518118  0.780704  0.766191
3  0.928167  0.616540  0.151223  0.664102  0.037299
4  0.717449  0.453904  0.384850  0.953102  0.757288

===== B =====
          c    (a, 0)    (a, 1)    (b, 0)    (b, 1)
0  0.909791  0.540405  0.814476  0.923961  0.935421
1  0.282063  0.679014  0.220417  0.511039  0.117898
2  0.766191  0.428563  0.915760  0.518118  0.780704
3  0.037299  0.928167  0.616540  0.151223  0.664102
4  0.757288  0.717449  0.453904  0.384850  0.953102
```
I don't care about the ordering of the columns here; most of the time we are completely agnostic to that with pandas. What I *do* care about is that the MultiIndex gets "flattened" in B.

Seems like a more desirable behavior would be to "promote" the target's column structure so that you always get A. That presents a tricky question about how to deal with complicated MultiIndex schemes on either side of the assignment, but at least for this basic case the current behavior feels wonky.

**Comment by jreback** [comment]
@brianthelion 

you are doing non-symmetric things, so you get a non-symmetric answer.

pandas will align the rhs of an assignment to the lhs. So when assigning a single level index to a multi-index it can easily just put it on level 0 (and fill the rest of the levels with ''), this is your ``df1_copy`` case.

however for ``df2_copy`` you are assigning a multi-index to a single level index. so the multi-level index is aligned to a single level. The only reasonable thing to do is to flatten it, making it into a single level index (which happens to be tuples). Not pretty, and one could argue that this should actually raise, but its rationale.

**Comment by brianthelion** [comment]
@jreback 

> The only reasonable thing to do is to flatten it, making it into a single level index (which happens to be tuples). Not pretty, and one could argue that this should actually raise, but its rationale.

I guess I am going to change my tack here and argue that flattening is not a reasonable thing to do. Why? My feeling is that flattening the assignor breaks a standard Python idiom, namely that *`__setitem__` assignment shouldn't fundamentally alter the assignor.* You might argue that Python idioms are imprecise beasts and that they don't exist until Guido says they do -- all of which are totally valid arguments. Nonetheless, I don't think you see too many instances in Pydom where that fail to uphold immutability across `__setitem__`.

In other words, we should never have a situation in which:
```python
>>> df1_copy[df2.columns] = df2
>>> assert df1_copy[df2.columns] == df2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/br/.virtualenvs/foo/local/lib/python2.7/site-packages/pandas/core/ops.py", line 912, in f
    return self._compare_frame(other, func, str_rep)
  File "/home/br/.virtualenvs/foo/local/lib/python2.7/site-packages/pandas/core/frame.py", line 3136, in _compare_frame
    raise ValueError('Can only compare identically-labeled '
ValueError: Can only compare identically-labeled DataFrame objects
```

I think maybe that's the most succinct way of phrasing it; apologies for being so circumspect previously. I would encourage the devs to consider changing the behavior to reflect something more idiomatic. I think there are a couple of good options available, and that a `raise` is probably not necessary.

**Comment by jreback** [comment]
What exactly are you proposing? This is a fundamentally non-symmetric operation.

**Comment by brianthelion** [comment]
IMHO, the most important thing is keeping the `__setitem__` interface consistent. If you assign something via `df['A'] = B` then you should be able to access it -- and not some fundamentally altered version of it -- via `df['A']`. Note that I'm not talking about *strict* immutability (`df['A'] is B`) here; just functional equivalence (`df['A'] == B`).

I don't disagree that something fundamentally non-symmetric is happening. I just can't think of any situations with `__setitem__` in which the expectation for interface adjustment *isn't* on the container object. In the present case specifically, I think it's much more natural to "upgrade" the assignee's index to a MultiIndex than to flatten the assignor's MultiIndex.

I am completely clueless about what an implementation of the above might look like. Naively, it seems like the most apt formulation of panda's indexing in general is as a set of operations on tree structures where leaf nodes reference individual columns (or rows) of data. I would be very surprised if this wasn't how it was already implemented, actually. From the tree-based perspective, combining any two indexes -- single-level, multi-level; it doesn't matter -- is just a question of building an edge at the right spot between two trees. I can imagine an API for moving entire subtrees up and down index levels. But again, that's just me speculating about something I haven't actually tried to understand in detail.

__TL;DR__ - Immutability across `__setitem__` is the most important thing here. A close second is that the containing data structure's interface should be the one that changes, if any. In this specific case, the container's "single" index should be upgraded to a MultiIndex.

**Comment by jreback** [comment]
@brianthelion your model of how a ``MultiIndex`` works is not correct. Pls have a look at ``core/index.py`` for more information. A MI is basically a fancy list of equal length tuples.

**Comment by brianthelion** [comment]
@jreback, please don't let my poor understanding of the implementation details detract from concerns raised about the `__setitem__` behavior. I think this issue is a point worthy of consideration by the devs insofar as it seems to violate a basic Python idiom. In the meantime I'll do my best to understand the current implementation and come back with something constructive.

**Comment by shoyer** [comment]
I actually agree with @brianthelion here -- the lack of symmetry here is surprising.

From an implementation perspective, I believe this would be a matter of updating `Index.reindex` with a special case so that it returns a MultiIndex if it has a MultiIndex target: https://github.com/pydata/pandas/blob/35d0893edfc01b2257826480e17cbe0632a24de3/pandas/core/index.py#L1707

Note that:

1. Reindex is not a particularly efficient operation *ever* (all the values need to be copied).
2. Reindex already does not always preserve Index subtype (e.g., try inserting string column names into a frame with only integer column names).

So on the whole, I don't see much of an issue with returning a new MultiIndex rather than an Index from Index.reindex.

**Comment by jreback** [comment]
well, this is NOT a ``reindex`` operation at all. rather it is an ``align`` type of operation.

```
In [108]: df2.align(df1,level=0)
Out[108]: 
(    a       b    
     0   1   0   1
 0 NaN NaN NaN NaN
 1 NaN NaN NaN NaN
 2 NaN NaN NaN NaN
 3 NaN NaN NaN NaN
 4 NaN NaN NaN NaN,           a                   b          
           0         1         0         1
 0  0.449161  0.977953  0.182016  0.215457
 1  0.050702  0.030895  0.233465  0.170092
 2  0.707819  0.455248  0.050476  0.953795
 3  0.708435  0.217373  0.508681  0.541064
 4  0.729345  0.935472  0.897516  0.776996)

```

However, it differs from this for a very important perspective, and the reasons this doesn't work like you think (and prob shoujd just raise instead).

- there is not control on *how* to align, e.g. which level, so doing anything is ambiguous and surprising here, e.g. no level argument *can* be specified
- changing the lhs of an expression from a less specialized object (``Index``) to a more specialized object (``MultiIndex``) is completely non-intuitive, and violates a host of principles
- changing the left hand index in a way that would so easily break any further operations would be so surpising (e.g. now you have to index via tuples, rather than via a string)
- pandas fundamentally tries to *align* the objects. when you are returning a NEW object, this is no problem. This is an inplace method and as such HAS to much more restricted on what it *can* change.
- imagine that this was allowed to morph to a MultiIndex on the lhs. So now I have to go inspect every set to be sure that I am NOT assigning a MultiIndex? seems odd to me
- note that this is similarly the case for say mixing a DatetimeIndex and an Object index (of say date strings). You don't get inference, merely concat.

so to me, this is by far the least surpising and practical thing to do. A MultiIndex is really just a tuple indexer. That is the most compatible object with an Index.

**Comment by shoyer** [comment]
Thanks for explaining your thoughts here @jreback. I'm not 100% sure I agree with you -- in particular, I *think* we try to make all indexing operations with `.loc` that work on a tuple index (e.g., the original example A) also work with a MultiIndex in the same way (example B), though I'm sure there are edge cases that means this is not the case in practice. Also, from a certain perspective, you can actually think of a MultiIndex as a more general type of Index, not a more specialized subtype. That said... this sort of operation is inherently quite messy, so this is quite far down my list of consistency fixes for pandas.
