### ISSUE TITLE
On demand imports failing in pandas.io.gbq

### ISSUE THREAD

**Issue by cgrin** [pydata/pandas#9713]
After upgrading to 0.16.0 BigQuery functionality is not working. Upon invoking pd.read_gbq(), the _test_imports() function is running, which in turn runs _importers(). Everything is all well and good up to here, but per pdb, once _importers() returns, the imported modules are not accessible and read_gbq() throws ```NameError: global name 'OAuth2WebServerFlow' is not defined```.

**Comment by jreback** [comment]
this is not tested on Travis at all though worked for me locally but certainly could be buggy
want to see if u can produce a patch?

**Comment by jreback** [comment]
@cgrin the way to fix this is to either: 

- put an actual import statement when these functions are used, e.g. (in ``get_credentials`` for ``OAuth2WebServerFlow``
- or maybe better to make these also global imports (like the other variables).

**Comment by cgrin** [comment]
Thanks for the info. I'll look into this when I get a chance. I think it makes sense to import in the function that needs to use the import, is there any advantage to the global imports method?

**Comment by jreback** [comment]
no, the global import really was just to avoid everything in pandas importing this (or trying to)

**Comment by jreback** [comment]
cc @jacobschaer

**Comment by cgrin** [comment]
Alright, I'll put together a PR that moves the imports into the functions that use them.

**Comment by azbones** [comment]
@cgrin @jreback-

@sean-schaefer and I were looking at refactoring for https://github.com/pydata/pandas/issues/8327 and this issue came up which prompted a couple questions for you:

Within the read_gbq() and to_gbq() functions, we are creating a Oauth connector object and doing various Oauth things, so we would have to move all of the required imports and objects into the namespace for each function (things like oauth2client.client and oauth2client.file.storage, etc). 

In order to refactor the code to remove the deprecated tools.run(), we have to get all the imports working. 

-Should we wait for @cgrin to refactor the existing code and get imports working?

If you share your strategy for managing this, we could work on it ourselves although it might be a couple weeks given we are doing a hackathon one night per week.

We were also going to look at the CI testing as even though we can't test against Google (despite talking to their engineering team to try to get a test account), we should at least catch things like this.

Let us know your thoughts.

cc @jacobschaer

**Comment by jreback** [comment]
I am going to put in @cgrin refactor for 0.16.1. (just needs a rebase) as its pretty straightforward and fixes the broken-ness now. Would fully +1 on testing! (esp on travis!).

**Comment by azbones** [comment]
@jreback Great.  @sean-schaefer, @jacobschaer and I will add travis CI testing to the top of our pandas backlog.

**Comment by jreback** [comment]
closed by #9722
